(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DESIGN_W=1672,DESIGN_H=941,KEY_W=64;
const NOTE_NAMES=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
const TRACK_COLORS=['#ff39d7','#39e7ff','#a855f7','#76ff3c','#ff9f43'];
const SCALE_NAMES=['Natural Minor','Major','Harmonic Minor','Melodic Minor','Chromatic'];
let fit=1,audio=null,audioUrl=null,audioCtx=null,audioBuffer=null,loadedFile=null;
let playing=false,raf=0,duration=0,overviewWave=[],pitchPoints=[],notes=[];
let selected=new Set(),hovered=-1,drag=null,tool='pointer',snap=true,viewMode='pitch',loop=false;
let viewStart=0,viewSeconds=9,tune=78,humanize=46,vibrato=62,formant=0;
let history=[],future=[],activeTrack=0,keyName='A Minor',scaleName='Natural Minor',reference=440;
const tracks=[
{name:'Lead Master',role:'Lead Vocals',file:null,muted:false,solo:false,offset:0},
{name:'Double L',role:'Vocal Double',file:null,muted:false,solo:false,offset:8},
{name:'Double R',role:'Vocal Double',file:null,muted:false,solo:false,offset:-6},
{name:'Harmony 1',role:'Harmony',file:null,muted:false,solo:false,offset:12},
{name:'Harmony 2',role:'Harmony',file:null,muted:false,solo:false,offset:-10}
];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmt=s=>{s=Math.max(0,s||0);const m=Math.floor(s/60),x=(s%60).toFixed(1).padStart(4,'0');return `${m}:${x}`};
const midiName=m=>{const x=Math.round(m);return NOTE_NAMES[(x%12+12)%12]+(Math.floor(x/12)-1)};
const qTime=t=>snap?Math.round(t/.0625)*.0625:t;
const qMidi=m=>snap?Math.round(m):m;
const median=a=>{if(!a.length)return 0;const x=[...a].sort((p,q)=>p-q);return x[Math.floor(x.length/2)]};
function status(t){$('#status').textContent=t}
function fitUI(){fit=clamp(Math.min(innerWidth/DESIGN_W,innerHeight/DESIGN_H),.58,1.2);document.documentElement.style.setProperty('--fit',fit);requestAnimationFrame(drawAll)}
function metrics(cv){const w=Math.max(1,cv.clientWidth),h=Math.max(1,cv.clientHeight),d=devicePixelRatio||1,rw=Math.round(w*d),rh=Math.round(h*d);if(cv.width!==rw||cv.height!==rh){cv.width=rw;cv.height=rh}const c=cv.getContext('2d');c.setTransform(d,0,0,d,0,0);return[c,w,h]}
function pointInCanvas(e){const cv=$('#pitch'),r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*(cv.clientWidth/r.width),y:(e.clientY-r.top)*(cv.clientHeight/r.height)}}
function cloneNotes(){return notes.map(n=>({...n,points:n.points.map(p=>({...p}))}))}
function pushHistory(){history.push(cloneNotes());if(history.length>50)history.shift();future=[];syncUndo()}
function syncUndo(){$('#undo').disabled=!history.length;$('#redo').disabled=!future.length}
function restore(s){notes=s.map(n=>({...n,points:n.points.map(p=>({...p}))}));selected.clear();drawPitch(audio?.currentTime||0);syncUndo()}
function undo(){if(!history.length)return;future.push(cloneNotes());restore(history.pop());status('Undo')}
function redo(){if(!future.length)return;history.push(cloneNotes());restore(future.pop());status('Redo')}
function waveformFrom(data,N=900){const out=[],step=Math.max(1,Math.floor(data.length/N));for(let i=0;i<N;i++){let peak=0,s=i*step,e=Math.min(data.length,s+step),jump=Math.max(1,Math.floor(step/100));for(let j=s;j<e;j+=jump)peak=Math.max(peak,Math.abs(data[j]));out.push(peak)}return out}
function downsample(data,srcRate,target=10000){const ratio=Math.max(1,Math.floor(srcRate/target)),n=Math.floor(data.length/ratio),out=new Float32Array(n);for(let i=0;i<n;i++)out[i]=data[i*ratio];return{data:out,rate:srcRate/ratio}}
function framePitch(data,rate,pos,size=1024){const end=Math.min(data.length,pos+size);let energy=0,peak=0;for(let i=pos;i<end;i+=2){const x=data[i]||0;energy+=x*x;peak=Math.max(peak,Math.abs(x))}energy=Math.sqrt(energy/Math.max(1,(end-pos)/2));if(energy<.008)return null;const minLag=Math.max(7,Math.floor(rate/1000)),maxLag=Math.min(Math.floor(rate/65),Math.floor(size/2));let best=0,bestCorr=-1;for(let lag=minLag;lag<=maxLag;lag++){let sum=0,a=0,b=0;for(let i=0;i<size-lag;i+=4){const x=data[pos+i]||0,y=data[pos+i+lag]||0;sum+=x*y;a+=x*x;b+=y*y}const corr=sum/Math.sqrt(a*b+1e-10);if(corr>bestCorr){bestCorr=corr;best=lag}}if(bestCorr<.50||!best)return null;const hz=rate/best;if(hz<65||hz>1000)return null;return{hz,midi:69+12*Math.log2(hz/440),conf:bestCorr,amp:clamp(energy*4.5,0,1),peak}}
function deOctave(pts){let last=null;return pts.map(p=>{let m=p.midi;if(last!==null){while(m-last>7)m-=12;while(last-m>7)m+=12}last=last===null?m:last*.72+m*.28;return{...p,midi:m}})}
function smoothPitch(pts){if(pts.length<5)return pts;return pts.map((p,i)=>{const w=pts.slice(Math.max(0,i-2),Math.min(pts.length,i+3)).filter(q=>Math.abs(q.time-p.time)<.14);return{...p,midi:median(w.map(q=>q.midi)),amp:w.reduce((s,q)=>s+q.amp,0)/w.length}})}
async function analyze(data,sampleRate){const ds=downsample(data,sampleRate),d=ds.data,r=ds.rate,hop=Math.round(r*.035),frame=1024,pts=[],maxFrames=Math.min(Math.floor((d.length-frame)/hop),9000);for(let k=0;k<maxFrames;k++){const pos=k*hop,p=framePitch(d,r,pos,frame);if(p)pts.push({time:pos/r,...p});if(k%180===0){status(`AI mapping vocal contour… ${Math.round(k/maxFrames*100)}%`);await new Promise(q=>setTimeout(q,0))}}return smoothPitch(deOctave(pts))}
function noteCenter(bucket){const strong=bucket.filter(p=>p.conf>.58);return median((strong.length?strong:bucket).map(p=>p.midi))}
function makeNote(bucket){const start=bucket[0].time,end=bucket.at(-1).time+.04,center=noteCenter(bucket);return{id:crypto.randomUUID?.()||Math.random().toString(36),start,end,originalStart:start,originalEnd:end,center,originalCenter:center,target:Math.round(center),points:bucket.map(p=>({...p})),colorIndex:Math.floor(Math.random()*3),tuneAmount:0}}
function segment(pts){if(!pts.length)return[];const out=[];let b=[],running=null,pending=0;const flush=()=>{if(b.length>=3&&b.at(-1).time-b[0].time>.075)out.push(makeNote(b));b=[];running=null;pending=0};for(const p of pts){const last=b.at(-1),gap=last?p.time-last.time:0;if(running===null)running=p.midi;const diff=Math.abs(p.midi-running);if(b.length&&gap>.14){flush()}else if(b.length&&diff>1.55&&b.at(-1).time-b[0].time>.10){pending++;if(pending>=2){const keep=b.splice(-1);flush();b=keep;running=b.length?b[0].midi:p.midi}}else pending=0;b.push(p);running=running===null?p.midi:running*.84+p.midi*.16}flush();return mergeNotes(out)}
function mergeNotes(src){if(!src.length)return[];let out=[];for(const n of src){if(!out.length){out.push(n);continue}const a=out.at(-1),gap=n.start-a.end,diff=Math.abs(n.center-a.center);if((gap<.075&&diff<.78)||(n.end-n.start<.11&&gap<.10&&diff<1.1)){const pts=[...a.points,...n.points],c=noteCenter(pts);a.end=n.end;a.originalEnd=n.end;a.points=pts;a.center=a.originalCenter=c;a.target=Math.round(c)}else out.push(n)}return out.filter(n=>n.end-n.start>.07)}
function fallbackNotes(){const base=[[.2,1.12,60.2],[1.15,2.4,61.1],[2.43,3.35,64.0],[3.4,4.0,63.2],[4.05,5.1,57.9],[5.15,6.4,60.4],[6.42,7.7,67.1],[7.74,8.75,68.0]];return base.map((x,i)=>{const pts=[];for(let t=x[0];t<x[1];t+=.035)pts.push({time:t,midi:x[2]+Math.sin(t*17+i)*.15+Math.sin(t*5)*.08,conf:.85,amp:.45+.25*Math.abs(Math.sin(t*9))});return makeNote(pts)})}
function currentPitch(n,p){const express=.18+(humanize/100)*.82,rawDelta=p.midi-n.originalCenter;return n.center+rawDelta*express}
function visibleRange(){const vis=notes.filter(n=>n.end>=viewStart&&n.start<=viewStart+viewSeconds);if(!vis.length)return[48,72];let mn=Math.floor(Math.min(...vis.flatMap(n=>n.points.length?n.points.map(p=>currentPitch(n,p)):[n.center])))-3,mx=Math.ceil(Math.max(...vis.flatMap(n=>n.points.length?n.points.map(p=>currentPitch(n,p)):[n.center])))+3;if(mx-mn<16){const mid=(mn+mx)/2;mn=Math.floor(mid-8);mx=Math.ceil(mid+8)}return[mn,mx]}
function pitchY(m,h,mn,mx){return 19+(mx-m)/(mx-mn)*(h-23)}
function geom(n,w,h,mn,mx){const pw=w-KEY_W,x=KEY_W+(n.start-viewStart)/viewSeconds*pw,x2=KEY_W+(n.end-viewStart)/viewSeconds*pw;return{x,x2,w:x2-x,y:pitchY(n.center,h,mn,mx)}}
function drawPiano(c,h,mn,mx){c.fillStyle='#07121d';c.fillRect(0,0,KEY_W,h);for(let m=Math.floor(mn);m<=Math.ceil(mx);m++){const y=pitchY(m,h,mn,mx),y2=pitchY(m-1,h,mn,mx),hh=Math.max(7,y2-y),pc=(m%12+12)%12,black=[1,3,6,8,10].includes(pc);c.fillStyle=black?'#071019':'#dbe4ec';c.fillRect(0,y-hh/2,black?38:KEY_W-1,hh-1);if(!black){c.fillStyle='#19344d';c.font='7px Inter';c.fillText(midiName(m),40,y+2)}}c.strokeStyle='#2d526e';c.beginPath();c.moveTo(KEY_W-.5,0);c.lineTo(KEY_W-.5,h);c.stroke()}
function drawGrid(c,w,h,mn,mx){const pw=w-KEY_W;for(let i=0;i<=18;i++){const x=KEY_W+i/18*pw;c.strokeStyle=i%2?'#ffffff06':'#24a6ff15';c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();c.fillStyle='#a8c6dc72';c.font='7px Inter';c.fillText((viewStart+i/18*viewSeconds).toFixed(1),x+3,11)}for(let m=Math.floor(mn);m<=Math.ceil(mx);m++){const y=pitchY(m,h,mn,mx),pc=(m%12+12)%12;c.fillStyle=[1,3,6,8,10].includes(pc)?'#ffffff018':'#ffffff008';c.fillRect(KEY_W,y-8,w-KEY_W,16);c.strokeStyle=pc===0?'#78a6ca2c':'#5c7f9d18';c.beginPath();c.moveTo(KEY_W,y);c.lineTo(w,y);c.stroke()}}
function drawRawTrace(c,w,h,mn,mx){if(!pitchPoints.length)return;const pw=w-KEY_W;c.strokeStyle='#19d6ff55';c.lineWidth=1.2;c.shadowColor='#19d6ff';c.shadowBlur=4;c.beginPath();let pen=false,last=-1;for(const p of pitchPoints){if(p.time<viewStart||p.time>viewStart+viewSeconds)continue;const x=KEY_W+(p.time-viewStart)/viewSeconds*pw,y=pitchY(p.midi,h,mn,mx);if(!pen||p.time-last>.11){c.moveTo(x,y);pen=true}else c.lineTo(x,y);last=p.time}c.stroke();c.shadowBlur=0}
function contourPoints(n,w,h,mn,mx){const pw=w-KEY_W,pts=n.points.filter(p=>p.time>=viewStart-.08&&p.time<=viewStart+viewSeconds+.08);if(pts.length<2){const g=geom(n,w,h,mn,mx);return[{x:g.x,y:g.y,amp:.5},{x:g.x2,y:g.y,amp:.5}]}return pts.map(p=>({x:KEY_W+(p.time-viewStart)/viewSeconds*pw,y:pitchY(currentPitch(n,p),h,mn,mx),rawY:pitchY(p.midi,h,mn,mx),amp:p.amp||.45,conf:p.conf||.7,time:p.time}))}
function blobPath(c,pts,base=7){if(pts.length<2)return;const top=pts.map(p=>({x:p.x,y:p.y-(base+clamp(p.amp,0,1)*8)})),bot=pts.map(p=>({x:p.x,y:p.y+(base+clamp(p.amp,0,1)*8)})).reverse();c.beginPath();c.moveTo(top[0].x,top[0].y);for(let i=1;i<top.length;i++){const a=top[i-1],b=top[i],mx=(a.x+b.x)/2;c.quadraticCurveTo(a.x,a.y,mx,(a.y+b.y)/2)}c.lineTo(top.at(-1).x,top.at(-1).y);for(let i=0;i<bot.length;i++){const a=i?bot[i-1]:top.at(-1),b=bot[i],mx=(a.x+b.x)/2;c.quadraticCurveTo(a.x,a.y,mx,(a.y+b.y)/2)}c.closePath()}
function drawTransition(c,a,b,w,h,mn,mx){const gap=b.start-a.end;if(gap<0||gap>.22)return;const pw=w-KEY_W,x1=KEY_W+(a.end-viewStart)/viewSeconds*pw,x2=KEY_W+(b.start-viewStart)/viewSeconds*pw;if(x2<KEY_W||x1>w)return;const y1=pitchY(a.center,h,mn,mx),y2=pitchY(b.center,h,mn,mx);c.strokeStyle='#ff5ad35a';c.lineWidth=4;c.shadowColor='#ff39d7';c.shadowBlur=7;c.beginPath();c.moveTo(x1,y1);c.bezierCurveTo(x1+(x2-x1)*.35,y1,x1+(x2-x1)*.65,y2,x2,y2);c.stroke();c.shadowBlur=0}
function drawBlob(c,n,i,w,h,mn,mx){if(n.end<viewStart||n.start>viewStart+viewSeconds)return;const pts=contourPoints(n,w,h,mn,mx),sel=selected.has(i),hot=i===hovered,g=geom(n,w,h,mn,mx);if(pts.at(-1).x<KEY_W||pts[0].x>w)return;const left=clamp(pts[0].x,KEY_W,w),right=clamp(pts.at(-1).x,KEY_W,w),grad=c.createLinearGradient(left,g.y,right,g.y);grad.addColorStop(0,sel?'#ff77ed':'#ff3ccf');grad.addColorStop(.45,'#c947ff');grad.addColorStop(1,'#7057ff');blobPath(c,pts,6);c.fillStyle=grad;c.globalAlpha=.86;c.shadowColor=sel?'#ffffff':'#d62cff';c.shadowBlur=sel?18:11;c.fill();c.globalAlpha=1;c.shadowBlur=0;c.strokeStyle=sel?'#fff':'#ffb6f0';c.lineWidth=sel?1.5:1;c.stroke();c.save();c.setLineDash([4,4]);c.strokeStyle=sel?'#ffffff90':'#ffffff3d';c.lineWidth=1;c.beginPath();c.moveTo(left,g.y);c.lineTo(right,g.y);c.stroke();c.restore();c.strokeStyle='#fff';c.lineWidth=1.35;c.shadowColor='#fff';c.shadowBlur=3;c.beginPath();pts.forEach((p,k)=>k?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke();c.shadowBlur=0;if(sel){c.strokeStyle='#23d8ffb0';c.lineWidth=1;c.beginPath();pts.forEach((p,k)=>k?c.lineTo(p.x,p.rawY??p.y):c.moveTo(p.x,p.rawY??p.y));c.stroke()}const ty=pitchY(Math.round(n.center),h,mn,mx);c.strokeStyle='#55f0ff44';c.beginPath();c.moveTo(left,ty);c.lineTo(right,ty);c.stroke();if(sel){c.fillStyle='#fff';c.fillRect(left-2,g.y-5,4,10);c.fillRect(right-2,g.y-5,4,10);c.fillStyle='#43edff';c.beginPath();c.arc((left+right)/2,g.y,4,0,Math.PI*2);c.fill();c.font='bold 8px Inter';c.fillStyle='#fff';const cents=Math.round((n.center-Math.round(n.center))*100);c.fillText(`${midiName(n.center)} ${cents>=0?'+':''}${cents}¢`,left+6,g.y-15)}else if(hot){c.font='bold 7px Inter';c.fillStyle='#fff';c.fillText(midiName(n.center),left+5,g.y-13)}}
function drawPitch(pos=0){const cv=$('#pitch');if(!cv)return;const[c,w,h]=metrics(cv);c.fillStyle='#06111d';c.fillRect(0,0,w,h);const[mn,mx]=visibleRange();drawPiano(c,h,mn,mx);drawGrid(c,w,h,mn,mx);drawRawTrace(c,w,h,mn,mx);for(let i=0;i<notes.length-1;i++)drawTransition(c,notes[i],notes[i+1],w,h,mn,mx);notes.forEach((n,i)=>drawBlob(c,n,i,w,h,mn,mx));if(duration&&pos>=viewStart&&pos<=viewStart+viewSeconds){const x=KEY_W+(pos-viewStart)/viewSeconds*(w-KEY_W);c.strokeStyle='#ff39d7';c.shadowColor='#ff39d7';c.shadowBlur=9;c.lineWidth=1.4;c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();c.shadowBlur=0}}
function drawOverview(pos=0){const cv=$('#overview');if(!cv)return;const[c,w,h]=metrics(cv);c.clearRect(0,0,w,h);const d=overviewWave.length?overviewWave:Array.from({length:350},(_,i)=>.12+.08*Math.abs(Math.sin(i*.2)));c.strokeStyle='#6e5dff';c.shadowColor='#8b5cf6';c.shadowBlur=5;c.beginPath();d.forEach((a,i)=>{const x=i/(d.length-1)*w,y=a*h*.42;c.moveTo(x,h/2-y);c.lineTo(x,h/2+y)});c.stroke();c.shadowBlur=0;if(duration){const sx=viewStart/duration*w,vw=Math.max(14,viewSeconds/duration*w);c.fillStyle='#5be7ff0b';c.strokeStyle='#7e7bff55';c.fillRect(sx,1,vw,h-2);c.strokeRect(sx+.5,1.5,vw-1,h-3);const x=pos/duration*w;c.strokeStyle='#ff39d7';c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}}
function drawAlign(){const box=$('#alignrows');if(!box)return;box.innerHTML='';tracks.slice(0,4).forEach((t,i)=>{const r=document.createElement('div');r.className='alignrow';r.innerHTML=`<div class="label"><i style="background:${TRACK_COLORS[i]}"></i><b>${t.name}</b><span>⛓</span></div><canvas></canvas><div class="offset">${t.offset>0?'+':''}${t.offset} ms</div>`;box.appendChild(r);const cv=r.querySelector('canvas'),[c,w,h]=metrics(cv);c.strokeStyle=TRACK_COLORS[i];c.shadowColor=TRACK_COLORS[i];c.shadowBlur=4;c.beginPath();for(let x=0;x<w;x+=3){const y=h/2+(Math.sin(x*.07+i)+Math.sin(x*.19+i*2))*(2.2+i*.15);x?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();c.shadowBlur=0})}
function drawAll(){drawOverview(audio?.currentTime||0);drawPitch(audio?.currentTime||0);drawAlign()}
function hitNote(x,y){const cv=$('#pitch'),w=cv.clientWidth,h=cv.clientHeight,[mn,mx]=visibleRange();let best=-1,bestDist=1e9;for(let i=notes.length-1;i>=0;i--){const n=notes[i];if(n.end<viewStart||n.start>viewStart+viewSeconds)continue;const g=geom(n,w,h,mn,mx),left=g.x-6,right=g.x2+6;if(x<left||x>right)continue;const d=Math.abs(y-g.y);if(d<20&&d<bestDist){best=i;bestDist=d}}return best}
function showTip(i,x,y){const el=$('#noteTooltip');if(i<0){el.style.display='none';return}const n=notes[i],cents=Math.round((n.center-Math.round(n.center))*100);el.innerHTML=`<b>${midiName(n.center)}</b> · ${cents>=0?'+':''}${cents}¢<br>${n.start.toFixed(2)}s → ${n.end.toFixed(2)}s`;el.style.display='block';el.style.left=`${x+12}px`;el.style.top=`${y+12}px`}
function edgeMode(i,x){if(i<0)return'none';const cv=$('#pitch'),w=cv.clientWidth,h=cv.clientHeight,[mn,mx]=visibleRange(),g=geom(notes[i],w,h,mn,mx);if(Math.abs(x-g.x)<8)return'left';if(Math.abs(x-g.x2)<8)return'right';return'body'}
function onDown(e){if(!notes.length)return;const p=pointInCanvas(e),i=hitNote(p.x,p.y);if(i<0){if(!e.shiftKey)selected.clear();drawPitch(audio?.currentTime||0);return}if(tool==='split'){const cv=$('#pitch'),time=viewStart+(p.x-KEY_W)/(cv.clientWidth-KEY_W)*viewSeconds,n=notes[i];if(time>n.start+.06&&time<n.end-.06){pushHistory();const left={...n,id:Math.random().toString(36),end:time,points:n.points.filter(q=>q.time<=time)},right={...n,id:Math.random().toString(36),start:time,points:n.points.filter(q=>q.time>=time)};notes.splice(i,1,left,right);selected=new Set([i+1]);$('#notes').textContent=`${notes.length} notes`;status('Note split');drawPitch(audio?.currentTime||0)}return}if(e.shiftKey){selected.has(i)?selected.delete(i):selected.add(i)}else if(!selected.has(i)){selected=new Set([i])}pushHistory();const n=notes[i];drag={i,mode:edgeMode(i,p.x),x:p.x,y:p.y,start:n.start,end:n.end,center:n.center,points:n.points.map(q=>({...q}))};$('#pitch').setPointerCapture?.(e.pointerId);drawPitch(audio?.currentTime||0)}
function onMove(e){const p=pointInCanvas(e),i=hitNote(p.x,p.y);hovered=i;showTip(i,p.x,p.y);const cv=$('#pitch');cv.style.cursor=i<0?'crosshair':edgeMode(i,p.x)==='body'?(tool==='pitch'?'ns-resize':'move'):'ew-resize';if(!drag){drawPitch(audio?.currentTime||0);return}const n=notes[drag.i],w=cv.clientWidth,h=cv.clientHeight,[mn,mx]=visibleRange(),dt=(p.x-drag.x)/(w-KEY_W)*viewSeconds,dm=-(p.y-drag.y)/(h-23)*(mx-mn);if(drag.mode==='left'){n.start=clamp(qTime(drag.start+dt),0,n.end-.06);const shift=n.start-drag.start;n.points=drag.points.filter(q=>q.time>=n.start).map(q=>({...q,time:q.time}));if(!n.points.length)n.points=drag.points.map(q=>({...q,time:q.time+shift}))}else if(drag.mode==='right'){n.end=Math.max(n.start+.06,qTime(drag.end+dt));n.points=drag.points.filter(q=>q.time<=n.end)}else if(tool==='pitch'){n.center=qMidi(drag.center+dm)}else{const moveTime=e.altKey||e.ctrlKey||e.metaKey||Math.abs(p.x-drag.x)>5;const movePitch=!e.altKey;if(moveTime){const s=qTime(drag.start+dt),shift=s-drag.start;n.start=Math.max(0,s);n.end=Math.max(n.start+.06,drag.end+shift);n.points=drag.points.map(q=>({...q,time:q.time+shift}))}if(movePitch)n.center=qMidi(drag.center+dm)}drawPitch(audio?.currentTime||0)}
function onUp(){drag=null}
function centerSelected(){if(!selected.size)return;pushHistory();selected.forEach(i=>{if(notes[i])notes[i].center=Math.round(notes[i].center)});status('Selected notes snapped to pitch');drawPitch(audio?.currentTime||0)}
function deleteSelected(){if(!selected.size)return;pushHistory();notes=notes.filter((_,i)=>!selected.has(i));selected.clear();$('#notes').textContent=`${notes.length} notes`;status('Notes deleted');drawPitch(audio?.currentTime||0)}
function selectAll(){selected=new Set(notes.map((_,i)=>i));drawPitch(audio?.currentTime||0)}
function updateViewLabel(){$('#viewportLabel').textContent=`Timeline · ${viewSeconds.toFixed(1)}s window`;$('#viewLabel').textContent=viewMode[0].toUpperCase()+viewMode.slice(1)}
function setTool(t){tool=t;$('#pointer').classList.toggle('active',t==='pointer');$('#pitchTool').classList.toggle('active',t==='pitch');$('#splitTool').classList.toggle('active',t==='split');$('#modeHint').textContent=t==='split'?'Click inside a blob to split':t==='pitch'?'Drag vertically = pitch only':'Drag blob = pitch + time · edges resize'}
function aiTune(){if(!notes.length)return;pushHistory();for(const n of notes){const target=Math.round(n.originalCenter),amt=(tune/100)*(1-humanize*.0035);n.center=n.center+(target-n.center)*amt;n.target=target;n.tuneAmount=amt}status(`AI Tune applied · ${tune}% strength · ${humanize}% humanize`);drawPitch(audio?.currentTime||0)}
function detectKey(){if(!pitchPoints.length){status('Import a vocal before key detection');return}const hist=new Array(12).fill(0);pitchPoints.forEach(p=>hist[(Math.round(p.midi)%12+12)%12]+=(p.conf||1)*(p.amp||.5));const major=[6.35,2.23,3.48,2.33,4.38,4.09,2.52,5.19,2.39,3.66,2.29,2.88],minor=[6.33,2.68,3.52,5.38,2.60,3.53,2.54,4.75,3.98,2.69,3.34,3.17];let best={score:-1e9,root:9,minor:true};for(let root=0;root<12;root++)for(const mi of [false,true]){const tpl=mi?minor:major;let score=0;for(let pc=0;pc<12;pc++)score+=hist[pc]*tpl[(pc-root+12)%12];if(score>best.score)best={score,root,minor:mi}}keyName=NOTE_NAMES[best.root]+' '+(best.minor?'Minor':'Major');scaleName=best.minor?'Natural Minor':'Major';$('#key').textContent=keyName;$('#scale').textContent=scaleName;status(`Key detected: ${keyName}`)}
function syncMacros(){$('#strength').nextElementSibling.textContent=tune+'%';$('#humanize').nextElementSibling.textContent=humanize+'%';$('#vibrato').nextElementSibling.textContent=vibrato+'%';$('#formantMacro').nextElementSibling.textContent=formant}
function loadPreset(name){const map={'Natural Vocal':[55,62,68,0],'Pop Tight':[92,25,32,0],'Trap Glide':[78,40,72,-1],'Choir Align':[84,38,48,0],'Transparent Fix':[68,58,55,0]},p=map[name];if(!p)return;[tune,humanize,vibrato,formant]=p;$('#strength').value=tune;$('#humanize').value=humanize;$('#vibrato').value=vibrato;$('#formantMacro').value=formant;syncMacros();$$('[data-p]').forEach(b=>b.classList.toggle('selected',b.dataset.p===name));status(`${name} preset loaded`);drawPitch(audio?.currentTime||0)}
function updateMeters(){if(!audio||audio.paused){$('#inMeter').style.width='0%';$('#outMeter').style.width='0%';$('#inDb').textContent='-∞ dB';$('#outDb').textContent='-∞ dB';return}const t=audio.currentTime,v=.32+.22*Math.abs(Math.sin(t*8))+.13*Math.abs(Math.sin(t*19));$('#inMeter').style.width=`${clamp(v,0,1)*100}%`;$('#outMeter').style.width=`${clamp(v*.82,0,1)*100}%`;$('#inDb').textContent=(20*Math.log10(v)).toFixed(1)+' dB';$('#outDb').textContent=(20*Math.log10(v*.82)).toFixed(1)+' dB';const n=notes.find(x=>t>=x.start&&t<=x.end),dev=n?Math.round((n.center-Math.round(n.center))*100):0;$('#devText').textContent=(dev>0?'+':'')+dev+'¢';$('#devNeedle').style.left=`${50+clamp(dev*.45,-45,45)}%`}
async function loadMaster(file){loadedFile=file;if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(file);audio=new Audio(audioUrl);tracks[0].file=file;$('#filename').textContent=file.name;$('#tracks .track[data-track="0"] small').textContent=file.name;$('#drop').classList.add('hidden');audio.onloadedmetadata=()=>{duration=audio.duration||0;$('#total').textContent=fmt(duration);$('#total2').textContent=fmt(duration)};audio.onended=()=>{playing=false;$('#play').textContent='▶'};status('Decoding vocal…');try{audioCtx=audioCtx||new AudioContext();const ab=await file.arrayBuffer();audioBuffer=await audioCtx.decodeAudioData(ab.slice(0));duration=audioBuffer.duration;const data=audioBuffer.getChannelData(0);overviewWave=waveformFrom(data);pitchPoints=await analyze(data,audioBuffer.sampleRate);notes=segment(pitchPoints);if(!notes.length)notes=fallbackNotes();history=[];future=[];selected.clear();viewStart=duration>viewSeconds?Math.min(duration-viewSeconds,Math.max(0,audio.currentTime||0)):0;$('#notes').textContent=`${notes.length} notes`;$('#total').textContent=fmt(duration);$('#total2').textContent=fmt(duration);detectKey();status(`Vocal contour ready · ${notes.length} musical note regions`);$('#insights').innerHTML=`<div class="insight"><i></i><div><b>${keyName}</b><small>Detected tonal center</small></div></div><div class="insight"><i style="background:#35eaff"></i><div><b>${notes.length} note regions</b><small>Organic pitch blobs ready for editing</small></div></div><div class="insight"><i style="background:#ffb336"></i><div><b>Raw + corrected contours</b><small>Cyan = source · white = current pitch</small></div></div>`;syncUndo();drawAll()}catch(err){console.error(err);notes=fallbackNotes();pitchPoints=notes.flatMap(n=>n.points);$('#notes').textContent=`${notes.length} notes`;status('Browser analysis fallback active');drawAll()}}
async function importFiles(files){const list=[...files].slice(0,5);if(!list.length)return;await loadMaster(list[0]);for(let i=1;i<list.length;i++){tracks[i].file=list[i];const tr=$(`.track[data-track="${i}"] small`);if(tr)tr.textContent=list[i].name}status(`${list.length} vocal track${list.length>1?'s':''} imported`)}
function play(){if(!audio){$('#file').click();return}if(playing){audio.pause();playing=false;$('#play').textContent='▶';return}if(audio.currentTime<viewStart||audio.currentTime>viewStart+viewSeconds)audio.currentTime=viewStart;audio.play();playing=true;$('#play').textContent='❚❚';tick()}
function stop(){if(!audio)return;audio.pause();playing=false;cancelAnimationFrame(raf);$('#play').textContent='▶';updateMeters()}
function tick(){if(!playing||!audio)return;const p=audio.currentTime;if(p>viewStart+viewSeconds*.92&&duration>viewSeconds)viewStart=clamp(p-viewSeconds*.16,0,duration-viewSeconds);if(loop&&p>=viewStart+viewSeconds)audio.currentTime=viewStart;$('#now').textContent=fmt(audio.currentTime);$('#now2').textContent=fmt(audio.currentTime);drawOverview(audio.currentTime);drawPitch(audio.currentTime);updateMeters();if(!audio.ended)raf=requestAnimationFrame(tick)}
function seekFromOverview(e){if(!duration)return;const r=$('#overview').getBoundingClientRect(),x=(e.clientX-r.left)/r.width;audio.currentTime=clamp(x,0,1)*duration;viewStart=clamp(audio.currentTime-viewSeconds*.2,0,Math.max(0,duration-viewSeconds));drawAll()}
function alignTracks(){tracks.slice(1,5).forEach((t,i)=>t.offset=[7,-5,11,-9][i]);status('AI Align · timing map updated against Lead Master');drawAlign()}
function exportSession(){const data={product:'VOX FREAK AI',version:'0.4-web',key:keyName,scale:scaleName,reference,tune,humanize,vibrato,formant,source:loadedFile?.name||null,notes:notes.map(n=>({start:n.start,end:n.end,originalCenter:n.originalCenter,currentCenter:n.center,target:n.target}))};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='vox-freak-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);status('Edit map exported as VOX FREAK session JSON')}
$('#add').onclick=$('#import').onclick=$('#drop').onclick=()=>$('#file').click();$('#file').onchange=e=>importFiles(e.target.files);document.body.ondragover=e=>e.preventDefault();document.body.ondrop=e=>{e.preventDefault();importFiles(e.dataTransfer.files)};$('#play').onclick=play;$('#stop').onclick=stop;$('#reset').onclick=()=>{if(audio)audio.currentTime=0;viewStart=0;drawAll()};$('#loop').onclick=()=>{loop=!loop;$('#loop').classList.toggle('active',loop);status(loop?'Loop enabled':'Loop disabled')};$('#overview').addEventListener('pointerdown',seekFromOverview);
$('#pointer').onclick=()=>setTool('pointer');$('#pitchTool').onclick=()=>setTool('pitch');$('#splitTool').onclick=()=>setTool('split');$('#undo').onclick=undo;$('#redo').onclick=redo;$('#snapBtn').onclick=()=>{snap=!snap;$('#snapBtn').classList.toggle('active',snap);$('#snapLabel').textContent=snap?'1/16':'Off';status(`Snap ${snap?'1/16':'off'}`)};$('#viewBtn').onclick=()=>{viewMode=viewMode==='pitch'?'drift':viewMode==='drift'?'modulation':'pitch';updateViewLabel();status(`View: ${viewMode}`);drawPitch(audio?.currentTime||0)};$('#zoomIn').onclick=()=>{viewSeconds=clamp(viewSeconds/1.35,2.5,28);updateViewLabel();drawAll()};$('#zoomOut').onclick=()=>{viewSeconds=clamp(viewSeconds*1.35,2.5,28);updateViewLabel();drawAll()};
const pc=$('#pitch');pc.addEventListener('pointerdown',onDown);pc.addEventListener('pointermove',onMove);pc.addEventListener('pointerup',onUp);pc.addEventListener('pointercancel',onUp);pc.addEventListener('pointerleave',()=>{$('#noteTooltip').style.display='none';hovered=-1;if(!drag)drawPitch(audio?.currentTime||0)});pc.addEventListener('dblclick',e=>{const p=pointInCanvas(e),i=hitNote(p.x,p.y);if(i>=0){selected=new Set([i]);centerSelected()}});pc.addEventListener('wheel',e=>{e.preventDefault();if(e.ctrlKey||e.metaKey){const factor=e.deltaY>0?1.18:.84;viewSeconds=clamp(viewSeconds*factor,2.5,28);updateViewLabel()}else{viewStart=clamp(viewStart+e.deltaY*.008*viewSeconds,0,Math.max(0,duration-viewSeconds))}drawAll()},{passive:false});
$('#tune').onclick=aiTune;$('#detect').onclick=detectKey;$('#natural').onclick=()=>{humanize=72;vibrato=68;$('#humanize').value=humanize;$('#vibrato').value=vibrato;syncMacros();status('Naturalize Vibrato · expressive contour preserved');drawPitch(audio?.currentTime||0)};$('#formant').onclick=()=>{formant=0;$('#formantMacro').value=0;syncMacros();status('Formant Protect armed for native DSP render')};$('#harmony').onclick=()=>status('Harmony Assist · slave intervals prepared');$('#align').onclick=$('#align2').onclick=alignTracks;$('#linkAll').onclick=()=>status('All slave vocals linked to Lead Master');$('#strength').oninput=e=>{tune=+e.target.value;syncMacros()};$('#humanize').oninput=e=>{humanize=+e.target.value;syncMacros();drawPitch(audio?.currentTime||0)};$('#vibrato').oninput=e=>{vibrato=+e.target.value;syncMacros();drawPitch(audio?.currentTime||0)};$('#formantMacro').oninput=e=>{formant=+e.target.value;syncMacros()};$$('[data-p]').forEach(b=>b.onclick=()=>loadPreset(b.dataset.p));
$('#key').onclick=()=>{const roots=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'],current=roots.findIndex(r=>keyName.startsWith(r+' ')),r=roots[(current+1+roots.length)%roots.length];keyName=`${r} ${keyName.includes('Major')?'Major':'Minor'}`;$('#key').textContent=keyName;status(`Key: ${keyName}`)};$('#scale').onclick=()=>{scaleName=SCALE_NAMES[(SCALE_NAMES.indexOf(scaleName)+1)%SCALE_NAMES.length];$('#scale').textContent=scaleName;status(`Scale: ${scaleName}`)};$('#reference').onclick=()=>{reference=reference===440?442:reference===442?432:440;$('#reference').textContent=reference+' Hz';status(`Reference: ${reference} Hz`)};
$$('.track').forEach((tr,i)=>{tr.addEventListener('click',e=>{if(e.target.closest('.ms'))return;activeTrack=i;$$('.track').forEach(x=>x.classList.remove('active'));tr.classList.add('active');status(i===0?'Lead Master pitch editor active':`${tracks[i].name} selected · alignment layer`)});const [m,s]=tr.querySelectorAll('.ms span');m.onclick=e=>{e.stopPropagation();tracks[i].muted=!tracks[i].muted;m.classList.toggle('on',tracks[i].muted);if(i===0&&audio)audio.muted=tracks[0].muted||tracks.some((t,j)=>j!==0&&t.solo)};s.onclick=e=>{e.stopPropagation();tracks[i].solo=!tracks[i].solo;s.classList.toggle('on',tracks[i].solo);if(audio)audio.muted=tracks[0].muted||tracks.some((t,j)=>j!==0&&t.solo)}});
$$('.nav button[data-view]').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.view;if(v==='align')document.querySelector('.alignment').scrollIntoView({behavior:'smooth',block:'center'});if(v==='ai')flashPanel(document.querySelector('.right'));if(v==='layers')flashPanel(document.querySelector('.left'));if(v==='tune')flashPanel(document.querySelector('.editor'))});function flashPanel(el){el.animate([{filter:'brightness(1)'},{filter:'brightness(1.35)'},{filter:'brightness(1)'}],{duration:420})}
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.tab==='controls')$('#insights').innerHTML='<div class="insight"><i></i><div><b>Gesture controls</b><small>Drag blob = pitch/time · edges resize · double-click centers</small></div></div><div class="insight"><i style="background:#35eaff"></i><div><b>Mouse wheel</b><small>Scroll timeline · Ctrl/Cmd+wheel zooms</small></div></div>';else if(b.dataset.tab==='analysis')$('#insights').innerHTML=`<div class="insight"><i></i><div><b>${notes.length} notes</b><small>${pitchPoints.length} voiced pitch frames</small></div></div><div class="insight"><i style="background:#ffb336"></i><div><b>${keyName}</b><small>${scaleName} · ${reference} Hz</small></div></div>`;else $('#insights').innerHTML='<div class="insight"><i></i><div><b>AI Tune</b><small>Center pitch while preserving the singer\'s modulation.</small></div></div>'});
$('#export').onclick=exportSession;
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();selectAll()}else if(e.key==='Delete'||e.key==='Backspace')deleteSelected();else if(e.key===' '&&!['INPUT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();play()}else if(e.key==='ArrowUp'&&selected.size){pushHistory();selected.forEach(i=>notes[i].center+=snap?1:.1);drawPitch(audio?.currentTime||0)}else if(e.key==='ArrowDown'&&selected.size){pushHistory();selected.forEach(i=>notes[i].center-=snap?1:.1);drawPitch(audio?.currentTime||0)}});
function updateViewLabel(){$('#viewportLabel').textContent=`Timeline · ${viewSeconds.toFixed(1)}s window`;$('#viewLabel').textContent=viewMode[0].toUpperCase()+viewMode.slice(1)}
function syncMacros(){$('#strength').nextElementSibling.textContent=tune+'%';$('#humanize').nextElementSibling.textContent=humanize+'%';$('#vibrato').nextElementSibling.textContent=vibrato+'%';$('#formantMacro').nextElementSibling.textContent=formant}
window.onresize=fitUI;notes=fallbackNotes();pitchPoints=notes.flatMap(n=>n.points);$('#notes').textContent=`${notes.length} demo notes`;$('#insights').innerHTML='<div class="insight"><i></i><div><b>Organic pitch editor ready</b><small>Import a vocal to map its continuous pitch contour.</small></div></div>';syncMacros();syncUndo();updateViewLabel();fitUI();drawAll();
})();