(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DESIGN_W=1672, DESIGN_H=941, KEY_W=58;
const COLORS=['#ff39d7','#39e7ff','#a855f7','#76ff3c','#ff9f43'];
const NOTE_NAMES=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
const KEYS=['C Major','C Minor','C♯ Minor','D Major','D Minor','E♭ Major','E Minor','F Major','F Minor','F♯ Minor','G Major','G Minor','A Major','A Minor','B♭ Major','B Minor'];
const SCALES=['Major','Natural Minor','Harmonic Minor','Melodic Minor','Pentatonic','Chromatic'];

let fit=1;
let audio=null, audioUrl=null, audioCtx=null, audioBuffer=null, loadedFile=null;
let playing=false, raf=0, duration=0, overviewWave=[];
let pitchPoints=[], notes=[], selected=-1, hovered=-1;
let tool='pointer', snap=true, viewMode='pitch', loop=false;
let viewStart=0, viewSeconds=8, tune=75, humanize=30, vibrato=50, formant=0;
let drag=null, history=[], future=[];
let activeTrack=0;
let trackState=[
  {name:'Lead Master',role:'Lead Vocals',file:null,muted:false,solo:false,offset:0},
  {name:'Double L',role:'Vocal Double',file:null,muted:false,solo:false,offset:8},
  {name:'Double R',role:'Vocal Double',file:null,muted:false,solo:false,offset:-6},
  {name:'Harmony 1',role:'Harmony',file:null,muted:false,solo:false,offset:12},
  {name:'Harmony 2',role:'Harmony',file:null,muted:false,solo:false,offset:-10}
];

const fmt=s=>{s=Math.max(0,s||0);const m=Math.floor(s/60),x=(s%60).toFixed(1).padStart(4,'0');return `${m}:${x}`};
const midiName=m=>{const x=Math.round(m);return NOTE_NAMES[(x%12+12)%12]+(Math.floor(x/12)-1)};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const qTime=t=>snap?Math.round(t/0.0625)*0.0625:t;
const qMidi=m=>snap?Math.round(m):m;

function fitUI(){fit=Math.min(innerWidth/DESIGN_W,innerHeight/DESIGN_H);fit=clamp(fit,.58,1.2);document.documentElement.style.setProperty('--fit',fit);requestAnimationFrame(drawAll)}
function canvasMetrics(cv){const w=Math.max(1,cv.clientWidth), h=Math.max(1,cv.clientHeight), d=devicePixelRatio||1;const rw=Math.round(w*d),rh=Math.round(h*d);if(cv.width!==rw||cv.height!==rh){cv.width=rw;cv.height=rh}const c=cv.getContext('2d');c.setTransform(d,0,0,d,0,0);return[c,w,h]}
function canvasPoint(e){const cv=$('#pitch'),r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*(cv.clientWidth/r.width),y:(e.clientY-r.top)*(cv.clientHeight/r.height)}}
function setStatus(text){const s=$('#status');if(s)s.textContent=text}
function flash(el){if(!el)return;el.classList.remove('flash');void el.offsetWidth;el.classList.add('flash')}
function setUndoState(){const u=$('#undo'),r=$('#redo');if(u)u.disabled=!history.length;if(r)r.disabled=!future.length}
function snapshot(){return notes.map(n=>({...n,points:(n.points||[]).map(p=>({...p}))}))}
function saveState(){history.push(snapshot());if(history.length>40)history.shift();future=[];setUndoState()}
function restore(state){notes=state.map(n=>({...n,points:(n.points||[]).map(p=>({...p}))}));selected=-1;hovered=-1;drawPitch(audio?.currentTime||0);setUndoState()}
function undo(){if(!history.length)return;future.push(snapshot());restore(history.pop());setStatus('Undo')}
function redo(){if(!future.length)return;history.push(snapshot());restore(future.pop());setStatus('Redo')}

function waveformFrom(data,N=720){const out=[],step=Math.max(1,Math.floor(data.length/N));for(let i=0;i<N;i++){let p=0,s=i*step,e=Math.min(data.length,s+step),jump=Math.max(1,Math.floor(step/100));for(let j=s;j<e;j+=jump)p=Math.max(p,Math.abs(data[j]));out.push(p)}return out}
function downsample(data,srcRate,target=8000){const ratio=Math.max(1,Math.floor(srcRate/target)),n=Math.floor(data.length/ratio),out=new Float32Array(n);for(let i=0;i<n;i++)out[i]=data[i*ratio];return{data:out,rate:srcRate/ratio}}
function framePitch(data,rate,pos,size=768){const end=Math.min(data.length,pos+size);let energy=0,zc=0,prev=data[pos]||0;for(let i=pos;i<end;i+=2){const x=data[i];energy+=x*x;if((x>=0)!=(prev>=0))zc++;prev=x}energy/=Math.max(1,(end-pos)/2);if(energy<.00005||zc<2)return null;const minLag=Math.max(7,Math.floor(rate/950)),maxLag=Math.min(Math.floor(rate/65),Math.floor(size/2));let best=0,bestCorr=-1;for(let lag=minLag;lag<=maxLag;lag++){let sum=0,a=0,b=0;for(let i=0;i<size-lag;i+=4){const x=data[pos+i]||0,y=data[pos+i+lag]||0;sum+=x*y;a+=x*x;b+=y*y}const corr=sum/Math.sqrt(a*b+1e-10);if(corr>bestCorr){bestCorr=corr;best=lag}}if(bestCorr<.48||!best)return null;const hz=rate/best;if(hz<65||hz>950)return null;return{hz,midi:69+12*Math.log2(hz/440),conf:bestCorr}}
async function analyze(data,sampleRate){const ds=downsample(data,sampleRate,8000),d=ds.data,r=ds.rate;const hop=Math.round(r*.045),frame=768,pts=[];const maxFrames=Math.min(Math.floor((d.length-frame)/hop),6200);for(let k=0;k<maxFrames;k++){const pos=k*hop,p=framePitch(d,r,pos,frame);if(p)pts.push({time:pos/r,...p});if(k%170===0){setStatus(`AI mapping pitch… ${Math.round(k/maxFrames*100)}%`);await new Promise(q=>setTimeout(q,0))}}return smoothPitch(pts)}
function median(arr){const a=[...arr].sort((x,y)=>x-y);return a[Math.floor(a.length/2)]}
function smoothPitch(pts){if(pts.length<5)return pts;return pts.map((p,i)=>{const win=pts.slice(Math.max(0,i-2),Math.min(pts.length,i+3)).filter(q=>Math.abs(q.time-p.time)<.18);return{...p,midi:median(win.map(q=>q.midi))}})}
function segment(pts){if(!pts.length)return[];const out=[];let bucket=[],running=null;const flush=()=>{if(bucket.length<2){bucket=[];running=null;return}const start=bucket[0].time,end=bucket.at(-1).time+.055;if(end-start<.07){bucket=[];running=null;return}const weighted=bucket.reduce((s,p)=>s+p.midi*p.conf,0)/Math.max(.001,bucket.reduce((s,p)=>s+p.conf,0));out.push({id:crypto.randomUUID?.()||Math.random().toString(36),start,end,midi:weighted,target:Math.round(weighted),original:weighted,points:bucket.map(p=>({time:p.time,midi:p.midi,conf:p.conf})),strength:75,humanize:30});bucket=[];running=null};for(const p of pts){const last=bucket.at(-1),gap=last?p.time-last.time:0;if(running===null)running=p.midi;const jump=Math.abs(p.midi-running);if(bucket.length&&(gap>.19||jump>1.15)){flush();running=p.midi}bucket.push(p);running=running*.82+p.midi*.18}flush();return mergeSegments(out)}
function mergeSegments(src){if(!src.length)return[];const out=[{...src[0]}];for(let i=1;i<src.length;i++){const a=out.at(-1),b=src[i],gap=b.start-a.end,diff=Math.abs(b.midi-a.midi);if(gap<.11&&diff<.85){const da=Math.max(.01,a.end-a.start),db=Math.max(.01,b.end-b.start);a.midi=(a.midi*da+b.midi*db)/(da+db);a.original=(a.original*da+b.original*db)/(da+db);a.target=Math.round(a.midi);a.end=b.end;a.points=[...(a.points||[]),...(b.points||[])]}else out.push({...b})}for(let i=1;i<out.length-1;i++){const n=out[i];if(n.end-n.start>=.12)continue;const l=out[i-1],r=out[i+1];if(n.start-l.end<.09&&Math.abs(n.midi-l.midi)<1.1){l.end=n.end;l.points=[...l.points,...n.points];out.splice(i,1);i--;continue}if(r.start-n.end<.09&&Math.abs(n.midi-r.midi)<1.1){r.start=n.start;r.points=[...n.points,...r.points];out.splice(i,1);i--}}return out}
function fallbackNotes(){return[[.40,1.15,64.2],[1.27,1.75,60.0],[1.87,2.70,62.8],[2.95,3.60,57.4],[3.72,4.55,61.2],[4.73,5.58,65.7],[5.85,6.82,68.1],[7.05,7.72,64.8]].map((x,i)=>({id:'demo'+i,start:x[0],end:x[1],midi:x[2],target:Math.round(x[2]),original:x[2],points:[],strength:75,humanize:30}))}

function timeWindow(pos){if(duration<=viewSeconds){viewStart=0;return 0}if(playing&&(pos<viewStart||pos>viewStart+viewSeconds))viewStart=clamp(pos-viewSeconds*.12,0,Math.max(0,duration-viewSeconds));return viewStart}
function drawOverview(pos=0){const cv=$('#overview');if(!cv)return;const[c,w,h]=canvasMetrics(cv);c.clearRect(0,0,w,h);c.strokeStyle='#ffffff14';c.beginPath();c.moveTo(0,h/2);c.lineTo(w,h/2);c.stroke();const d=overviewWave.length?overviewWave:Array.from({length:300},(_,i)=>.14+.07*Math.sin(i*.24)+.04*Math.sin(i*.83));const g=c.createLinearGradient(0,0,w,0);g.addColorStop(0,'#4f46e5');g.addColorStop(.5,'#8b5cf6');g.addColorStop(1,'#5d5bd9');c.strokeStyle=g;c.shadowColor='#8b5cf6';c.shadowBlur=6;c.beginPath();d.forEach((a,i)=>{const x=i/(d.length-1)*w,y=Math.abs(a)*h*.42;c.moveTo(x,h/2-y);c.lineTo(x,h/2+y)});c.stroke();c.shadowBlur=0;if(duration){const s=viewStart/duration*w,v=Math.max(16,Math.min(w-s,viewSeconds/duration*w));c.fillStyle='#d9e9ff0d';c.fillRect(s,0,v,h);c.strokeStyle='#a48bff55';c.strokeRect(s+.5,.5,v-1,h-1);const x=clamp(pos/duration*w,0,w);c.strokeStyle='#ff36d7';c.shadowColor='#ff36d7';c.shadowBlur=8;c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();c.shadowBlur=0}}
function visibleMidiRange(){const vis=notes.filter(n=>n.end>=viewStart&&n.start<=viewStart+viewSeconds);if(!vis.length)return[48,72];let mn=Math.floor(Math.min(...vis.map(n=>n.midi)))-4,mx=Math.ceil(Math.max(...vis.map(n=>n.midi)))+4;if(mx-mn<18){const mid=(mn+mx)/2;mn=Math.floor(mid-9);mx=Math.ceil(mid+9)}return[mn,mx]}
function pitchY(m,h,minMidi,maxMidi){return 20+(maxMidi-m)/(maxMidi-minMidi)*(h-24)}
function noteGeometry(n,w,h,minMidi,maxMidi){const plotW=w-KEY_W,x=KEY_W+(n.start-viewStart)/viewSeconds*plotW,x2=KEY_W+(n.end-viewStart)/viewSeconds*plotW,y=pitchY(n.midi,h,minMidi,maxMidi);return{x,y,w:x2-x,h:20}}
function drawPiano(c,h,minMidi,maxMidi){c.fillStyle='#07121d';c.fillRect(0,0,KEY_W,h);for(let m=Math.floor(minMidi);m<=Math.ceil(maxMidi);m++){const y=pitchY(m,h,minMidi,maxMidi),y2=pitchY(m-1,h,minMidi,maxMidi),hh=Math.max(7,y2-y),pc=(m%12+12)%12,black=[1,3,6,8,10].includes(pc);c.fillStyle=black?'#071019':'#dbe4ec';c.fillRect(0,y-hh/2,black?35:KEY_W-1,hh-1);if(!black){c.fillStyle='#183047';c.font='7px Inter';c.fillText(midiName(m),37,y+2)}}c.strokeStyle='#294963';c.beginPath();c.moveTo(KEY_W-.5,0);c.lineTo(KEY_W-.5,h);c.stroke()}
function tracePointY(p,n,h,mn,mx){let m=p.midi;if(viewMode==='drift')m=n.midi+(p.midi-n.original)*.65;if(viewMode==='modulation')m=n.midi+(p.midi-n.original)*(vibrato/100);return pitchY(m,h,mn,mx)}
function drawRawTrace(c,w,h,mn,mx){if(!pitchPoints.length)return;const plotW=w-KEY_W,start=viewStart,end=viewStart+viewSeconds;c.strokeStyle='#27c9ff5c';c.lineWidth=1;c.shadowColor='#27c9ff';c.shadowBlur=3;c.beginPath();let pen=false,lastT=-1;for(const p of pitchPoints){if(p.time<start||p.time>end)continue;const x=KEY_W+(p.time-start)/viewSeconds*plotW,y=pitchY(p.midi,h,mn,mx);if(!pen||p.time-lastT>.14){c.moveTo(x,y);pen=true}else c.lineTo(x,y);lastT=p.time}c.stroke();c.shadowBlur=0}
function drawPitch(pos=0){const cv=$('#pitch');if(!cv)return;const[c,w,h]=canvasMetrics(cv);c.fillStyle='#06111d';c.fillRect(0,0,w,h);const[mn,mx]=visibleMidiRange(),plotW=w-KEY_W,start=timeWindow(pos);drawPiano(c,h,mn,mx);for(let i=0;i<=16;i++){const x=KEY_W+i/16*plotW;c.strokeStyle=i%2?'#ffffff07':'#24a6ff18';c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();c.fillStyle='#a8c6dc75';c.font='7px Inter';c.fillText((start+i/16*viewSeconds).toFixed(1),x+3,11)}for(let m=Math.floor(mn);m<=Math.ceil(mx);m++){const y=pitchY(m,h,mn,mx);c.strokeStyle=(m%12===0)?'#5b8bb52c':'#5c7f9d16';c.beginPath();c.moveTo(KEY_W,y);c.lineTo(w,y);c.stroke()}drawRawTrace(c,w,h,mn,mx);const vis=notes.length?notes:fallbackNotes();vis.forEach((n,i)=>{if(n.end<start||n.start>start+viewSeconds)return;const g=noteGeometry(n,w,h,mn,mx);if(g.w<2)return;const active=i===selected,hot=i===hovered,gx=Math.max(KEY_W,g.x),gw=Math.min(w,g.x+g.w)-gx;const grad=c.createLinearGradient(gx,g.y,gx+gw,g.y);grad.addColorStop(0,active?'#ff75ef':'#d92cff');grad.addColorStop(1,(i%3===1)?'#6f57ff':'#ff38d2');c.fillStyle=grad;c.shadowColor=active?'#ffffff':'#b82cff';c.shadowBlur=active?16:9;c.beginPath();c.roundRect(gx,g.y-10,gw,20,8);c.fill();c.shadowBlur=0;c.strokeStyle=active?'#ffffff':'#f6d0ffcf';c.lineWidth=active?1.7:1;c.stroke();const pts=n.points?.filter(p=>p.time>=start&&p.time<=start+viewSeconds)||[];c.strokeStyle='#ffffff';c.lineWidth=1.2;c.beginPath();if(pts.length>1){pts.forEach((p,k)=>{const px=KEY_W+(p.time-start)/viewSeconds*plotW,py=tracePointY(p,n,h,mn,mx);k?c.lineTo(px,py):c.moveTo(px,py)})}else{for(let k=0;k<12;k++){const px=g.x+g.w*k/11,py=g.y+Math.sin(k*1.5+i)*2.3*(vibrato/50);k?c.lineTo(px,py):c.moveTo(px,py)}}c.stroke();c.strokeStyle='#ffffff40';c.setLineDash([3,3]);c.beginPath();c.moveTo(gx+4,g.y);c.lineTo(gx+gw-4,g.y);c.stroke();c.setLineDash([]);if(active||hot){c.fillStyle='#fff';c.font='bold 7px Inter';c.fillText(`${midiName(n.midi)}  ${Math.round((n.midi-Math.round(n.midi))*100)}¢`,gx+6,g.y-14)}if(active){c.fillStyle='#73f2ff';c.shadowColor='#36eaff';c.shadowBlur=6;c.fillRect(gx-3,g.y-5,5,10);c.fillRect(gx+gw-2,g.y-5,5,10);c.shadowBlur=0}});if(duration&&pos>=start&&pos<=start+viewSeconds){const x=KEY_W+(pos-start)/viewSeconds*plotW;c.strokeStyle='#ff36d7';c.shadowColor='#ff36d7';c.shadowBlur=8;c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();c.shadowBlur=0}}
function drawAlign(){const box=$('#alignrows');if(!box)return;box.innerHTML='';trackState.slice(0,4).forEach((t,i)=>{const r=document.createElement('div');r.className='alignrow';r.innerHTML=`<div class="label"><i style="background:${COLORS[i]}"></i><b>${t.name}</b><span>⛓</span></div><canvas></canvas><div class="offset">${t.offset>0?'+':''}${t.offset} ms</div>`;box.appendChild(r);const[c,w,h]=canvasMetrics(r.querySelector('canvas'));c.strokeStyle=COLORS[i];c.shadowColor=COLORS[i];c.shadowBlur=5;c.beginPath();for(let x=0;x<w;x+=3){const a=(Math.sin(x*.045+i)+Math.sin(x*.13+i*2))*.18+.28*Math.sin(x*.011+i);const y=h/2+a*h*.5;x?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();c.shadowBlur=0})}
function drawAll(){drawOverview(audio?.currentTime||0);drawPitch(audio?.currentTime||0);drawAlign()}

function updateMeters(){if(!audio||audio.paused){$('#inMeter').style.width='0%';$('#outMeter').style.width='0%';$('#inDb').textContent='-∞ dB';$('#outDb').textContent='-∞ dB';return}const t=audio.currentTime,a=.38+.23*Math.sin(t*8)+.11*Math.sin(t*19),v=clamp(Math.abs(a),.04,.95),db=x=>20*Math.log10(Math.max(1e-5,x));$('#inMeter').style.width=(v*100)+'%';$('#outMeter').style.width=(v*.82*100)+'%';$('#inDb').textContent=db(v).toFixed(1)+' dB';$('#outDb').textContent=db(v*.82).toFixed(1)+' dB';const near=notes.find(n=>t>=n.start&&t<=n.end),dev=near?Math.round((near.original-Math.round(near.original))*100):0;$('#devText').textContent=(dev>0?'+':'')+dev+'¢';$('#devNeedle').style.left=(50+clamp(dev*.45,-45,45))+'%'}
async function load(file){loadedFile=file;trackState[0].file=file;trackState[0].role=file.name;renderTracks();if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(file);audio=new Audio(audioUrl);$('#filename').textContent=file.name;$('#drop').classList.add('hidden');setStatus('Loading and mapping vocal…');audio.onloadedmetadata=()=>{duration=audio.duration||0;$('#total').textContent=fmt(duration);$('#total2').textContent=fmt(duration)};audio.onended=()=>{if(loop){audio.currentTime=viewStart;audio.play();tick()}else{playing=false;$('#play').textContent='▶'}};try{audioCtx=audioCtx||new AudioContext();const ab=await file.arrayBuffer();audioBuffer=await audioCtx.decodeAudioData(ab.slice(0));duration=audioBuffer.duration;const data=audioBuffer.getChannelData(0);overviewWave=waveformFrom(data);pitchPoints=await analyze(data,audioBuffer.sampleRate);notes=segment(pitchPoints);if(!notes.length)notes=fallbackNotes();history=[];future=[];selected=-1;viewStart=duration>viewSeconds?Math.min(Math.max(0,audio.currentTime-viewSeconds*.1),duration-viewSeconds):0;$('#notes').textContent=notes.length+' notes';$('#total').textContent=fmt(duration);$('#total2').textContent=fmt(duration);const avg=pitchPoints.length?pitchPoints.reduce((s,p)=>s+p.conf,0)/pitchPoints.length:0;setStatus(`AI analysis complete · ${notes.length} musical note regions`);$('#insights').innerHTML=`<div class="insight"><i></i><div><b>Pitch map ready</b><small>${notes.length} editable note regions detected.</small></div></div><div class="insight"><i style="background:#ffb336"></i><div><b>Pitch drift detected</b><small>Use AI Tune or drag notes directly.</small></div></div><div class="insight"><i style="background:#35eaff"></i><div><b>Pitch confidence ${Math.round(avg*100)}%</b><small>Raw F0 trace is displayed behind the note blobs.</small></div></div>`;drawAll();setUndoState()}catch(e){console.error(e);notes=fallbackNotes();$('#notes').textContent=notes.length+' demo notes';setStatus('Audio loaded · browser pitch analysis fallback active');drawAll()}}
function tick(){if(!playing||!audio)return;const p=audio.currentTime;$('#now').textContent=fmt(p);$('#now2').textContent=fmt(p);timeWindow(p);drawOverview(p);drawPitch(p);updateMeters();if(loop&&p>=viewStart+viewSeconds)audio.currentTime=viewStart;if(audio.ended&&!loop){playing=false;$('#play').textContent='▶';return}raf=requestAnimationFrame(tick)}
function play(){if(!audio){$('#file').click();return}if(playing){audio.pause();playing=false;$('#play').textContent='▶';updateMeters();return}if(audio.currentTime<viewStart||audio.currentTime>viewStart+viewSeconds)audio.currentTime=viewStart;audio.play();playing=true;$('#play').textContent='❚❚';tick()}
function stop(){if(!audio)return;audio.pause();audio.currentTime=viewStart;playing=false;cancelAnimationFrame(raf);$('#play').textContent='▶';$('#now').textContent=fmt(viewStart);$('#now2').textContent=fmt(viewStart);updateMeters();drawAll()}

function noteHit(x,y){const cv=$('#pitch'),w=cv.clientWidth,h=cv.clientHeight,[mn,mx]=visibleMidiRange();for(let i=notes.length-1;i>=0;i--){const g=noteGeometry(notes[i],w,h,mn,mx);if(x>=g.x-6&&x<=g.x+g.w+6&&y>=g.y-14&&y<=g.y+14){let edge=null;if(Math.abs(x-g.x)<8)edge='left';else if(Math.abs(x-(g.x+g.w))<8)edge='right';return{i,g,edge}}}return null}
function showTip(hit,x,y){const t=$('#noteTooltip');if(!hit){t.style.display='none';return}const n=notes[hit.i],cents=Math.round((n.midi-Math.round(n.midi))*100);t.innerHTML=`<b>${midiName(n.midi)}</b> · ${cents>=0?'+':''}${cents}¢<br>${n.start.toFixed(2)}s → ${n.end.toFixed(2)}s`;t.style.display='block';t.style.left=(x+12)+'px';t.style.top=(y+12)+'px'}
function pointerDown(e){if(!notes.length)return;const p=canvasPoint(e),hit=noteHit(p.x,p.y);selected=hit?hit.i:-1;if(!hit){drawPitch(audio?.currentTime||0);return}const n=notes[hit.i];if(tool==='split'){const w=$('#pitch').clientWidth,time=viewStart+(p.x-KEY_W)/(w-KEY_W)*viewSeconds;if(time>n.start+.05&&time<n.end-.05){saveState();const t=qTime(time),left={...n,id:Math.random().toString(36),end:t,points:n.points.filter(q=>q.time<=t)},right={...n,id:Math.random().toString(36),start:t,points:n.points.filter(q=>q.time>=t)};notes.splice(hit.i,1,left,right);selected=hit.i+1;$('#notes').textContent=notes.length+' notes';setStatus('Note split');drawPitch(audio?.currentTime||0)}return}saveState();drag={i:hit.i,x:p.x,y:p.y,midi:n.midi,start:n.start,end:n.end,points:n.points.map(q=>({...q})),edge:hit.edge,mode:tool};$('#pitch').setPointerCapture?.(e.pointerId);drawPitch(audio?.currentTime||0)}
function pointerMove(e){const p=canvasPoint(e),hit=noteHit(p.x,p.y);hovered=hit?hit.i:-1;showTip(hit,p.x,p.y);const cv=$('#pitch');cv.style.cursor=hit?.edge?'ew-resize':hit?(tool==='pitch'?'ns-resize':'grab'):(tool==='split'?'crosshair':'default');if(!drag){drawPitch(audio?.currentTime||0);return}const w=cv.clientWidth,h=cv.clientHeight,[mn,mx]=visibleMidiRange(),n=notes[drag.i],dx=p.x-drag.x,dy=p.y-drag.y;if(drag.edge){const dt=dx/(w-KEY_W)*viewSeconds;if(drag.edge==='left')n.start=clamp(qTime(drag.start+dt),0,n.end-.05);else n.end=Math.max(n.start+.05,qTime(drag.end+dt))}else{const semis=-dy/(h-24)*(mx-mn);n.midi=qMidi(drag.midi+semis);if(drag.mode==='pointer'){const dt=dx/(w-KEY_W)*viewSeconds,shift=qTime(dt);n.start=Math.max(0,drag.start+shift);n.end=Math.max(n.start+.05,drag.end+shift);n.points=drag.points.map(q=>({...q,time:q.time+shift}))}}setStatus(`${midiName(n.midi)} · ${Math.round((n.midi-Math.round(n.midi))*100)}¢ · ${n.start.toFixed(2)}s`);drawPitch(audio?.currentTime||0)}
function pointerUp(){if(drag)setStatus('Note edit committed · Undo available');drag=null}
function dblClick(e){const p=canvasPoint(e),hit=noteHit(p.x,p.y);if(!hit)return;saveState();const n=notes[hit.i];n.midi=Math.round(n.midi);selected=hit.i;setStatus(`Snapped ${midiName(n.midi)} to pitch center`);drawPitch(audio?.currentTime||0)}

function aiTune(){if(!notes.length)return;saveState();const keyText=$('#key').textContent,rootName=keyText.split(' ')[0],rootMap={'C':0,'C♯':1,'D':2,'E♭':3,'E':4,'F':5,'F♯':6,'G':7,'A':9,'B♭':10,'B':11},root=rootMap[rootName]??9;const minor=[0,2,3,5,7,8,10],major=[0,2,4,5,7,9,11],set=new Set((keyText.includes('Minor')?minor:major).map(x=>(x+root)%12));for(const n of notes){let candidates=[];for(let d=-3;d<=3;d++){const m=Math.round(n.midi)+d;if(set.has((m%12+12)%12))candidates.push(m)}const target=candidates.sort((a,b)=>Math.abs(a-n.midi)-Math.abs(b-n.midi))[0]??Math.round(n.midi),amount=tune/100*(1-humanize/170);n.midi=n.midi+(target-n.midi)*amount;n.target=target}setStatus(`AI Tune applied · ${tune}% strength · ${humanize}% humanize`);drawPitch(audio?.currentTime||0)}
function detectKey(){if(!pitchPoints.length){setStatus('Import a vocal to detect key');return}const hist=new Array(12).fill(0);pitchPoints.forEach(p=>hist[(Math.round(p.midi)%12+12)%12]+=p.conf);const root=hist.indexOf(Math.max(...hist));$('#key').textContent=NOTE_NAMES[root]+' Minor';$('#scale').textContent='Natural Minor';setStatus(`Key estimated: ${$('#key').textContent}`)}
function autoAlign(){trackState.forEach((t,i)=>t.offset=i===0?0:Math.round((Math.sin(i*1.7)*9+i*2)));drawAlign();setStatus('AI Align complete · Master/Slave offsets recalculated')}
function preset(name){$$('.presetgrid button').forEach(b=>b.classList.toggle('selected',b.dataset.p===name));const p={"Natural Vocal":[55,55,55,0],"Pop Tight":[90,22,35,0],"Trap Glide":[78,35,62,-1],"Choir Align":[82,28,46,0],"Transparent Fix":[68,52,42,0]}[name];if(p){[tune,humanize,vibrato,formant]=p;$('#strength').value=tune;$('#humanize').value=humanize;$('#vibrato').value=vibrato;$('#formantMacro').value=formant;syncMacros()}setStatus(name+' preset loaded')}
function syncMacros(){$('#strength').nextElementSibling.textContent=tune+'%';$('#humanize').nextElementSibling.textContent=humanize+'%';$('#vibrato').nextElementSibling.textContent=vibrato+'%';$('#formantMacro').nextElementSibling.textContent=(formant>0?'+':'')+formant}
function setTool(t){tool=t;$('#pointer').classList.toggle('active',t==='pointer');$('#pitchTool').classList.toggle('active',t==='pitch');$('#splitTool').classList.toggle('active',t==='split');$('#modeHint').textContent=t==='pointer'?'Drag = pitch + time · edges resize':t==='pitch'?'Pitch tool · vertical correction only':'Split tool · click inside a note'}
function renderTracks(){$$('.track').forEach((el,i)=>{const t=trackState[i];el.classList.toggle('active',i===activeTrack);el.classList.toggle('muted',t.muted);el.classList.toggle('solo',t.solo);const sub=el.querySelector('small');if(sub)sub.textContent=t.file?t.file.name:t.role;const ms=el.querySelectorAll('.ms span');if(ms[0])ms[0].classList.toggle('on',t.muted);if(ms[1])ms[1].classList.toggle('on',t.solo)})}
function cycleText(el,arr){const i=arr.indexOf(el.textContent);el.textContent=arr[(i+1+arr.length)%arr.length]}
function renderAssistantTab(tab){$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const box=$('#insights');if(tab==='suggestions')box.innerHTML='<div class="insight"><i></i><div><b>Pitch map ready</b><small>Select or drag a note to edit it.</small></div></div><div class="insight"><i style="background:#ffb336"></i><div><b>AI Tune available</b><small>Strength and Humanize control correction depth.</small></div></div>';if(tab==='controls')box.innerHTML='<div class="insight"><i style="background:#35eaff"></i><div><b>Manual editing</b><small>Pointer moves pitch/time. Pitch tool constrains vertical. Edge handles resize.</small></div></div><div class="insight"><i style="background:#a855f7"></i><div><b>Keyboard</b><small>⌘/Ctrl+Z Undo · Delete removes selected note · Space Play/Pause.</small></div></div>';if(tab==='analysis')box.innerHTML=`<div class="insight"><i></i><div><b>${notes.length} note regions</b><small>${pitchPoints.length} raw F0 samples · ${viewSeconds.toFixed(1)}s visible window.</small></div></div><div class="insight"><i style="background:#35eaff"></i><div><b>Selected</b><small>${selected>=0?midiName(notes[selected].midi)+' · '+notes[selected].start.toFixed(2)+'s':'No note selected'}</small></div></div>`}

function bind(){
  $('#add').onclick=$('#import').onclick=$('#drop').onclick=()=>$('#file').click();
  $('#file').onchange=e=>{const fs=[...e.target.files];if(fs[0])load(fs[0]);fs.slice(1,5).forEach((f,j)=>{trackState[j+1].file=f});renderTracks()};
  document.body.ondragover=e=>e.preventDefault();document.body.ondrop=e=>{e.preventDefault();const fs=[...e.dataTransfer.files];if(fs[0])load(fs[0]);fs.slice(1,5).forEach((f,j)=>trackState[j+1].file=f);renderTracks()};
  $('#play').onclick=play;$('#stop').onclick=stop;$('#reset').onclick=()=>{viewStart=0;if(audio)audio.currentTime=0;stop()};$('#loop').onclick=()=>{loop=!loop;$('#loop').classList.toggle('active',loop);setStatus(loop?'Loop enabled':'Loop disabled')};
  $('#pointer').onclick=()=>setTool('pointer');$('#pitchTool').onclick=()=>setTool('pitch');$('#splitTool').onclick=()=>setTool('split');$('#undo').onclick=undo;$('#redo').onclick=redo;
  $('#zoomIn').onclick=()=>{viewSeconds=Math.max(1.5,viewSeconds/1.35);$('#viewportLabel').textContent=`Timeline · ${viewSeconds.toFixed(1)}s window`;drawAll()};$('#zoomOut').onclick=()=>{viewSeconds=Math.min(40,viewSeconds*1.35);$('#viewportLabel').textContent=`Timeline · ${viewSeconds.toFixed(1)}s window`;drawAll()};
  $('#snapBtn').onclick=()=>{snap=!snap;$('#snapBtn').classList.toggle('active',snap);$('#snapLabel').textContent=snap?'1/16':'Off';setStatus(snap?'Snap enabled':'Snap disabled')};
  $('#viewBtn').onclick=()=>{viewMode=viewMode==='pitch'?'drift':viewMode==='drift'?'modulation':'pitch';$('#viewLabel').textContent=viewMode[0].toUpperCase()+viewMode.slice(1);setStatus('View: '+viewMode);drawPitch(audio?.currentTime||0)};
  const pc=$('#pitch');pc.addEventListener('pointerdown',pointerDown);pc.addEventListener('pointermove',pointerMove);pc.addEventListener('pointerup',pointerUp);pc.addEventListener('pointercancel',pointerUp);pc.addEventListener('dblclick',dblClick);pc.addEventListener('pointerleave',()=>{hovered=-1;$('#noteTooltip').style.display='none';if(!drag)drawPitch(audio?.currentTime||0)});
  pc.addEventListener('wheel',e=>{e.preventDefault();if(e.ctrlKey||e.metaKey){viewSeconds=clamp(viewSeconds*(e.deltaY>0?1.15:.87),1.5,40)}else{viewStart=clamp(viewStart+e.deltaY*.0025*viewSeconds,0,Math.max(0,duration-viewSeconds))}$('#viewportLabel').textContent=`Timeline · ${viewSeconds.toFixed(1)}s window`;drawAll()},{passive:false});
  $('#overview').addEventListener('pointerdown',e=>{if(!duration)return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width;const t=clamp(x*duration,0,duration);viewStart=clamp(t-viewSeconds/2,0,Math.max(0,duration-viewSeconds));if(audio)audio.currentTime=t;drawAll()});
  $('#tune').onclick=aiTune;$('#align').onclick=$('#align2').onclick=autoAlign;$('#linkAll').onclick=()=>{trackState.slice(1).forEach(t=>t.offset=0);drawAlign();setStatus('All slave layers linked to Lead Master')};$('#detect').onclick=detectKey;$('#natural').onclick=()=>{vibrato=62;$('#vibrato').value=62;syncMacros();setStatus('Naturalize Vibrato · expressive modulation preserved');drawPitch(audio?.currentTime||0)};$('#formant').onclick=()=>{formant=0;$('#formantMacro').value=0;syncMacros();setStatus('Formant Protect enabled · neutral formant shift')};$('#harmony').onclick=()=>{activeTrack=3;renderTracks();flash($('.left'));setStatus('Harmony Assist · Harmony 1 selected as slave layer')};
  $('#strength').oninput=e=>{tune=+e.target.value;syncMacros()};$('#humanize').oninput=e=>{humanize=+e.target.value;syncMacros();drawPitch(audio?.currentTime||0)};$('#vibrato').oninput=e=>{vibrato=+e.target.value;syncMacros();drawPitch(audio?.currentTime||0)};$('#formantMacro').oninput=e=>{formant=+e.target.value;syncMacros()};
  $$('.presetgrid button').forEach(b=>b.onclick=()=>preset(b.dataset.p));
  $('#key').onclick=()=>{cycleText($('#key'),KEYS);setStatus('Key: '+$('#key').textContent)};$('#scale').onclick=()=>{cycleText($('#scale'),SCALES);setStatus('Scale: '+$('#scale').textContent)};$('#reference').onclick=()=>{$('#reference').textContent=$('#reference').textContent==='440 Hz'?'442 Hz':'440 Hz';setStatus('Reference '+$('#reference').textContent)};
  $$('.track').forEach((el,i)=>{el.onclick=e=>{if(e.target.closest('.ms'))return;activeTrack=i;renderTracks();setStatus(trackState[i].name+' selected')}});
  $$('.ms span').forEach((sp,idx)=>sp.onclick=e=>{e.stopPropagation();const row=sp.closest('.track'),i=+row.dataset.track,which=idx%2===0?'muted':'solo';trackState[i][which]=!trackState[i][which];renderTracks();setStatus(`${trackState[i].name} ${which==='muted'?(trackState[i].muted?'muted':'unmuted'):(trackState[i].solo?'solo':'solo off')}`);if(i===0&&audio)audio.muted=trackState[0].muted});
  $$('.nav button[data-view]').forEach(b=>b.onclick=()=>{$$('.nav button[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.view;if(v==='tune')flash($('.editor'));if(v==='align')flash($('.alignment'));if(v==='layers')flash($('.left'));if(v==='ai')flash($('.right'));setStatus(v[0].toUpperCase()+v.slice(1)+' workspace')});
  $$('.tabs button').forEach(b=>b.onclick=()=>renderAssistantTab(b.dataset.tab));
  $('#export').onclick=()=>{if(!audioUrl){setStatus('Import a vocal before export');return}const a=document.createElement('a');a.href=audioUrl;a.download=(loadedFile?.name?.replace(/\.[^.]+$/,'')||'vox-freak')+'-preview';a.click();setStatus('Source preview exported · corrected render requires native resynthesis core')};
  window.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if(tag==='INPUT')return;if(e.code==='Space'){e.preventDefault();play()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}if((e.key==='Delete'||e.key==='Backspace')&&selected>=0){e.preventDefault();saveState();notes.splice(selected,1);selected=-1;$('#notes').textContent=notes.length+' notes';drawPitch(audio?.currentTime||0);setStatus('Selected note deleted')}});
  window.addEventListener('resize',fitUI);
}

bind();fitUI();notes=fallbackNotes();$('#notes').textContent=notes.length+' demo notes';setUndoState();syncMacros();renderTracks();renderAssistantTab('suggestions');drawAll();
})();
