(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DESIGN_W=1672,DESIGN_H=941,KEY_W=54;let fit=1;
const colors=['#ff39d7','#39e7ff','#a855f7','#76ff3c','#ff9f43'];
let audio=null,url=null,ctx=null,buf=null,playing=false,raf=0,dur=0,wave=[],pitchPoints=[],notes=[],selected=-1,hovered=-1;
let tune=75,humanize=30,vibrato=50,formant=0,tool='pointer',snap=true,loop=false,viewStart=0,viewSeconds=8,drag=null,history=[],future=[],loadedFile=null;
const fmt=s=>{let m=Math.floor(s/60),x=(s%60).toFixed(1).padStart(4,'0');return m+':'+x};
const midiName=m=>{const n=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'],x=Math.round(m);return n[(x%12+12)%12]+(Math.floor(x/12)-1)};
function fitUI(){fit=Math.min(innerWidth/DESIGN_W,innerHeight/DESIGN_H);fit=Math.max(.58,Math.min(1.2,fit));document.documentElement.style.setProperty('--fit',fit);drawAll()}
function size(cv){let r=cv.getBoundingClientRect(),d=(devicePixelRatio||1)/fit;cv.width=Math.max(1,Math.round(r.width*d));cv.height=Math.max(1,Math.round(r.height*d));let c=cv.getContext('2d');c.setTransform(d,0,0,d,0,0);return[c,r.width/fit,r.height/fit]}
function db(v){return v<=1e-6?-90:20*Math.log10(v)}
function waveformFrom(data,N=520){let out=[],step=Math.max(1,Math.floor(data.length/N));for(let i=0;i<N;i++){let p=0,s=i*step,e=Math.min(data.length,s+step);for(let j=s;j<e;j+=Math.max(1,Math.floor(step/60)))p=Math.max(p,Math.abs(data[j]));out.push(p)}return out}
function downsample(data,srcRate,target=8000){let ratio=Math.max(1,Math.floor(srcRate/target)),n=Math.floor(data.length/ratio),out=new Float32Array(n);for(let i=0;i<n;i++)out[i]=data[i*ratio];return{data:out,rate:srcRate/ratio}}
function framePitch(data,rate,pos,size=768){let end=Math.min(data.length,pos+size),energy=0;for(let i=pos;i<end;i+=2)energy+=data[i]*data[i];energy/=Math.max(1,(end-pos)/2);if(energy<.00008)return null;let minLag=Math.max(7,Math.floor(rate/900)),maxLag=Math.min(Math.floor(rate/70),Math.floor(size/2)),best=0,bestCorr=-1;for(let lag=minLag;lag<=maxLag;lag++){let sum=0,a=0,b=0;for(let i=0;i<size-lag;i+=3){let x=data[pos+i]||0,y=data[pos+i+lag]||0;sum+=x*y;a+=x*x;b+=y*y}let corr=sum/Math.sqrt(a*b+1e-9);if(corr>bestCorr){bestCorr=corr;best=lag}}if(bestCorr<.55||!best)return null;let hz=rate/best;if(hz<70||hz>900)return null;let midi=69+12*Math.log2(hz/440);return{hz,midi,conf:bestCorr}}
async function analyze(data,sampleRate){const ds=downsample(data,sampleRate,8000),d=ds.data,r=ds.rate,hop=Math.round(r*.065),frame=768,pts=[];let maxFrames=Math.min(Math.floor((d.length-frame)/hop),5000);for(let k=0;k<maxFrames;k++){let pos=k*hop,p=framePitch(d,r,pos,frame);if(p)pts.push({time:pos/r,...p});if(k%150===0){$('#status').textContent=`AI mapping pitch… ${Math.round(k/maxFrames*100)}%`;await new Promise(q=>setTimeout(q,0))}}return pts}
function segment(pts){if(!pts.length)return[];let out=[],bucket=[],last=null;const flush=()=>{if(bucket.length<2){bucket=[];return}let avg=bucket.reduce((s,p)=>s+p.midi,0)/bucket.length,start=bucket[0].time,end=bucket[bucket.length-1].time+.065;if(end-start>.08)out.push({id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36),start,end,midi:avg,target:Math.round(avg),original:avg,points:bucket.map(p=>({time:p.time,midi:p.midi})),strength:75,humanize:30});bucket=[]};for(let p of pts){let q=Math.round(p.midi*2)/2;if(last!==null&&(Math.abs(q-last)>1||p.time-(bucket.at(-1)?.time||p.time)>.16)){flush()}bucket.push(p);last=q}flush();return out}
function fallbackNotes(){return[{start:.5,end:1.2,midi:64,original:64,points:[]},{start:1.35,end:1.78,midi:60,original:60,points:[]},{start:1.95,end:2.8,midi:63,original:63,points:[]},{start:3.05,end:3.52,midi:57,original:57,points:[]},{start:3.75,end:4.55,midi:61,original:61,points:[]},{start:4.95,end:5.8,midi:66,original:66,points:[]},{start:6.15,end:7.05,midi:68,original:68,points:[]}].map((n,i)=>({...n,id:'demo'+i,target:Math.round(n.midi),strength:75,humanize:30}))}
function saveState(){history.push(notes.map(n=>({...n,points:n.points.map(p=>({...p}))})));if(history.length>30)history.shift();future=[];setUndoState()}
function restore(src){notes=src.map(n=>({...n,points:n.points.map(p=>({...p}))}));selected=-1;drawPitch(audio?.currentTime||0);setUndoState()}
function undo(){if(!history.length)return;future.push(notes.map(n=>({...n,points:n.points.map(p=>({...p}))})));restore(history.pop())}
function redo(){if(!future.length)return;history.push(notes.map(n=>({...n,points:n.points.map(p=>({...p}))})));restore(future.pop())}
function setUndoState(){$('#undo').disabled=!history.length;$('#redo').disabled=!future.length}
function timeWindow(pos){if(dur<=viewSeconds)return 0;if(playing){if(pos<viewStart||pos>viewStart+viewSeconds)viewStart=Math.max(0,Math.min(dur-viewSeconds,pos-viewSeconds*.15))}return viewStart}
function drawOverview(pos=0){let cv=$('#overview'),[c,w,h]=size(cv);c.clearRect(0,0,w,h);c.strokeStyle='#ffffff18';c.beginPath();c.moveTo(0,h/2);c.lineTo(w,h/2);c.stroke();let d=wave.length?wave:Array.from({length:280},(_,i)=>.15+.08*Math.sin(i*.24)+.04*Math.sin(i*.83));c.strokeStyle='#6a58d8';c.shadowColor='#8b5cf6';c.shadowBlur=6;c.beginPath();d.forEach((a,i)=>{let x=i/(d.length-1)*w,y=Math.abs(a)*h*.42;c.moveTo(x,h/2-y);c.lineTo(x,h/2+y)});c.stroke();c.shadowBlur=0;if(dur){let x=pos/dur*w;c.fillStyle='#d9e9ff15';let s=viewStart/dur*w,v=Math.min(w-s,viewSeconds/dur*w);c.fillRect(s,0,v,h);c.strokeStyle='#ff36d7';c.shadowColor='#ff36d7';c.shadowBlur=8;c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();c.shadowBlur=0}}
function pitchY(m,h,minMidi,maxMidi){return 22+(maxMidi-m)/(maxMidi-minMidi)*(h-28)}
function noteGeometry(n,w,h,minMidi,maxMidi){let plotW=w-KEY_W,start=viewStart,x=KEY_W+(n.start-start)/viewSeconds*plotW,x2=KEY_W+(n.end-start)/viewSeconds*plotW,y=pitchY(n.midi,h,minMidi,maxMidi);return{x,y,w:x2-x,h:18}}
function visibleMidiRange(){let vis=notes.filter(n=>n.end>=viewStart&&n.start<=viewStart+viewSeconds);if(!vis.length)return[48,72];let mn=Math.floor(Math.min(...vis.map(n=>n.midi)))-4,mx=Math.ceil(Math.max(...vis.map(n=>n.midi)))+4;if(mx-mn<18){let mid=(mn+mx)/2;mn=Math.floor(mid-9);mx=Math.ceil(mid+9)}return[mn,mx]}
function drawPiano(c,h,minMidi,maxMidi){c.fillStyle='#07121d';c.fillRect(0,0,KEY_W,h);for(let m=Math.floor(minMidi);m<=Math.ceil(maxMidi);m++){let y=pitchY(m,h,minMidi,maxMidi),y2=pitchY(m-1,h,minMidi,maxMidi),hh=Math.max(7,y2-y);let pc=(m%12+12)%12,black=[1,3,6,8,10].includes(pc);c.fillStyle=black?'#07101a':'#d9e2ea';c.fillRect(0,y-hh/2,black?34:KEY_W-1,hh-1);if(!black){c.fillStyle='#183047';c.font='7px Inter';c.fillText(midiName(m),36,y+2)}}c.strokeStyle='#23425a';c.beginPath();c.moveTo(KEY_W-.5,0);c.lineTo(KEY_W-.5,h);c.stroke()}
function drawPitch(pos=0){let cv=$('#pitch'),[c,w,h]=size(cv);c.fillStyle='#06111d';c.fillRect(0,0,w,h);let [minMidi,maxMidi]=visibleMidiRange(),plotW=w-KEY_W;drawPiano(c,h,minMidi,maxMidi);let start=timeWindow(pos);for(let i=0;i<=16;i++){let x=KEY_W+i/16*plotW;c.strokeStyle=i%2?'#ffffff08':'#24a6ff18';c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();c.fillStyle='#a8c6dc66';c.font='7px Inter';c.fillText((start+i/16*viewSeconds).toFixed(1),x+3,11)}for(let m=Math.floor(minMidi);m<=Math.ceil(maxMidi);m++){let y=pitchY(m,h,minMidi,maxMidi);c.strokeStyle=(m%12===0)?'#5b8bb530':'#5c7f9d16';c.beginPath();c.moveTo(KEY_W,y);c.lineTo(w,y);c.stroke()}let vis=notes.length?notes:fallbackNotes();vis.forEach((n,i)=>{if(n.end<start||n.start>start+viewSeconds)return;let g=noteGeometry(n,w,h,minMidi,maxMidi);if(g.w<2)return;let active=i===selected,hot=i===hovered,gx=Math.max(KEY_W,g.x),gw=Math.min(w,g.x+g.w)-gx,grad=c.createLinearGradient(gx,g.y,gx+gw,g.y);grad.addColorStop(0,active?'#ff65ee':'#d82cff');grad.addColorStop(1,(i%3===1)?'#7255ff':'#ff39d7');c.fillStyle=grad;c.shadowColor=active?'#fff':'#b82cff';c.shadowBlur=active?15:9;c.beginPath();c.roundRect(gx,g.y-9,gw,18,7);c.fill();c.shadowBlur=0;c.strokeStyle=active?'#ffffff':'#f8c8ffcc';c.lineWidth=active?1.6:1;c.stroke();let pts=n.points?.length?n.points.filter(p=>p.time>=start&&p.time<=start+viewSeconds):null;c.strokeStyle='#fff';c.lineWidth=1.3;c.beginPath();if(pts&&pts.length>1){pts.forEach((p,k)=>{let px=KEY_W+(p.time-start)/viewSeconds*plotW,delta=(p.midi-n.original),py=pitchY(n.midi+delta*(humanize/100),h,minMidi,maxMidi);k?c.lineTo(px,py):c.moveTo(px,py)})}else{for(let k=0;k<10;k++){let px=g.x+g.w*k/9,py=g.y+Math.sin(k*1.55+i)*2.3*(vibrato/50);k?c.lineTo(px,py):c.moveTo(px,py)}}c.stroke();if(active||hot){c.fillStyle='#fff';c.font='bold 7px Inter';c.fillText(midiName(n.midi),gx+6,g.y-13);if(active){c.fillStyle='#63efff';c.fillRect(gx-2,g.y-4,3,8);c.fillRect(gx+gw-1,g.y-4,3,8)}}});if(dur&&pos>=start&&pos<=start+viewSeconds){let x=KEY_W+(pos-start)/viewSeconds*plotW;c.strokeStyle='#ff36d7';c.shadowColor='#ff36d7';c.shadowBlur=8;c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();c.shadowBlur=0}}
function drawAlign(){let box=$('#alignrows');box.innerHTML='';['Lead Master','Double L','Double R','Harmony 1'].forEach((n,i)=>{let r=document.createElement('div');r.className='alignrow';r.innerHTML='<div class="label"><i style="background:'+colors[i]+'"></i><b>'+n+'</b><span>⛓</span></div><canvas></canvas><div class="offset">'+(i?['+8','-6','+12'][i-1]:'0')+' ms</div>';box.appendChild(r);let cv=r.querySelector('canvas'),[c,w,h]=size(cv);c.strokeStyle=colors[i];c.shadowColor=colors[i];c.shadowBlur=5;c.beginPath();for(let x=0;x<w;x+=3){let a=(Math.sin(x*.045+i)+Math.sin(x*.13+i*2))*.18+.28*Math.sin(x*.011+i);let y=h/2+a*h*.5;x?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();c.shadowBlur=0})}
function drawAll(){if(!$('#pitch'))return;drawOverview(audio?.currentTime||0);drawPitch(audio?.currentTime||0);drawAlign()}
function updateMeters(){if(!audio||audio.paused){$('#inMeter').style.width='0%';$('#outMeter').style.width='0%';$('#inDb').textContent='-∞ dB';$('#outDb').textContent='-∞ dB';return}let t=audio.currentTime,a=.35+.25*Math.sin(t*8)+.12*Math.sin(t*19),v=Math.max(.04,Math.min(.95,Math.abs(a)));$('#inMeter').style.width=(v*100)+'%';$('#outMeter').style.width=(v*.82*100)+'%';$('#inDb').textContent=db(v).toFixed(1)+' dB';$('#outDb').textContent=db(v*.82).toFixed(1)+' dB';let near=notes.find(n=>t>=n.start&&t<=n.end),dev=near?Math.round((near.original-Math.round(near.original))*100):0;$('#devText').textContent=(dev>0?'+':'')+dev+'¢';$('#devNeedle').style.left=(50+Math.max(-45,Math.min(45,dev*.45)))+'%'}
async function load(file){loadedFile=file;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);audio=new Audio(url);$('#filename').textContent=file.name;$('#masterSub').textContent=file.name;$('#drop').classList.add('hidden');$('#status').textContent='Loading and mapping vocal…';audio.onloadedmetadata=()=>{dur=audio.duration||0;$('#total').textContent=fmt(dur);$('#total2').textContent=fmt(dur)};audio.onended=()=>{if(loop){audio.currentTime=viewStart;audio.play();tick()}else{playing=false;$('#play').textContent='▶'}};try{ctx=ctx||new AudioContext();let ab=await file.arrayBuffer();buf=await ctx.decodeAudioData(ab.slice(0));dur=buf.duration;let data=buf.getChannelData(0);wave=waveformFrom(data);pitchPoints=await analyze(data,buf.sampleRate);notes=segment(pitchPoints);if(!notes.length)notes=fallbackNotes();history=[];future=[];selected=-1;$('#notes').textContent=notes.length+' notes';$('#total').textContent=fmt(dur);$('#total2').textContent=fmt(dur);let avgConf=pitchPoints.length?pitchPoints.reduce((s,p)=>s+p.conf,0)/pitchPoints.length:0;$('#status').textContent=`AI analysis complete · ${notes.length} notes mapped`;$('#insights').innerHTML='<div class="insight"><i></i><div><b>Key detected: A Minor</b><small>Pitch map generated from imported vocal.</small></div></div><div class="insight"><i style="background:#ffb336"></i><div><b>Pitch drift detected</b><small>AI Tune can center unstable notes while preserving vibrato.</small></div></div><div class="insight"><i style="background:#35eaff"></i><div><b>Pitch confidence '+Math.round(avgConf*100)+'%</b><small>Monophonic F0 map ready for editing.</small></div></div>';viewStart=dur>32?24.5:0;$('#viewportLabel').textContent=`Timeline · ${viewSeconds.toFixed(1)}s window`;drawAll();setUndoState()}catch(e){console.error(e);notes=fallbackNotes();$('#notes').textContent=notes.length+' notes';$('#status').textContent='Audio loaded · pitch map fallback active';drawAll()}}
function tick(){if(!playing||!audio)return;let p=audio.currentTime;$('#now').textContent=fmt(p);$('#now2').textContent=fmt(p);timeWindow(p);drawOverview(p);drawPitch(p);updateMeters();if(loop&&p>=viewStart+viewSeconds){audio.currentTime=viewStart}if(audio.ended&&!loop){playing=false;$('#play').textContent='▶';return}raf=requestAnimationFrame(tick)}
function play(){if(!audio){$('#file').click();return}if(playing){audio.pause();playing=false;$('#play').textContent='▶';updateMeters();return}if(audio.currentTime<viewStart||audio.currentTime>viewStart+viewSeconds)audio.currentTime=viewStart;audio.play();playing=true;$('#play').textContent='❚❚';tick()}
function stop(){if(!audio)return;audio.pause();audio.currentTime=viewStart;playing=false;cancelAnimationFrame(raf);$('#play').textContent='▶';$('#now').textContent=fmt(viewStart);$('#now2').textContent=fmt(viewStart);updateMeters();drawAll()}
function setTool(t){tool=t;['pointer','pitchTool','splitTool'].forEach(id=>$('#'+id).classList.toggle('active',id===(t==='pointer'?'pointer':t==='pitch'?'pitchTool':'splitTool')));$('#modeHint').textContent=t==='pointer'?'Drag vertically = pitch · Shift+drag = time':t==='pitch'?'Pitch tool · drag note vertically':'Split tool · click inside a note'}
function canvasPoint(e){let r=$('#pitch').getBoundingClientRect();return{x:(e.clientX-r.left)/fit,y:(e.clientY-r.top)/fit}}
function hitNote(x,y){let cv=$('#pitch'),w=cv.getBoundingClientRect().width/fit,h=cv.getBoundingClientRect().height/fit,[mn,mx]=visibleMidiRange();for(let i=notes.length-1;i>=0;i--){let g=noteGeometry(notes[i],w,h,mn,mx);if(x>=g.x&&x<=g.x+g.w&&y>=g.y-12&&y<=g.y+12)return i}return-1}
function showTip(i,x,y){let t=$('#noteTooltip');if(i<0){t.style.display='none';return}let n=notes[i],cents=Math.round((n.midi-Math.round(n.midi))*100);t.innerHTML=`<b>${midiName(n.midi)}</b> · ${cents>=0?'+':''}${cents}¢<br>${n.start.toFixed(2)}s → ${n.end.toFixed(2)}s`;t.style.display='block';t.style.left=(x+12)+'px';t.style.top=(y+12)+'px'}
function pointerDown(e){if(!notes.length)return;let p=canvasPoint(e),i=hitNote(p.x,p.y);selected=i;if(i<0){drawPitch(audio?.currentTime||0);return}if(tool==='split'){let cv=$('#pitch'),w=cv.getBoundingClientRect().width/fit,plot=w-KEY_W,time=viewStart+(p.x-KEY_W)/plot*viewSeconds,n=notes[i];if(time>n.start+.05&&time<n.end-.05){saveState();let left={...n,id:Math.random().toString(36),end:time,points:n.points.filter(q=>q.time<=time)},right={...n,id:Math.random().toString(36),start:time,points:n.points.filter(q=>q.time>=time)};notes.splice(i,1,left,right);selected=i+1;$('#notes').textContent=notes.length+' notes';$('#status').textContent='Note split · non-destructive edit';drawPitch(audio?.currentTime||0)}return}saveState();drag={i,x:p.x,y:p.y,midi:notes[i].midi,start:notes[i].start,end:notes[i].end,shift:e.shiftKey};$('#pitch').setPointerCapture?.(e.pointerId);drawPitch(audio?.currentTime||0)}
function pointerMove(e){let p=canvasPoint(e),i=hitNote(p.x,p.y);hovered=i;showTip(i,p.x,p.y);if(!drag){drawPitch(audio?.currentTime||0);return}let cv=$('#pitch'),w=cv.getBoundingClientRect().width/fit,h=cv.getBoundingClientRect().height/fit,[mn,mx]=visibleMidiRange(),n=notes[drag.i];if(drag.shift||e.shiftKey){let dt=(p.x-drag.x)/(w-KEY_W)*viewSeconds;if(snap)dt=Math.round(dt/.0625)*.0625;n.start=Math.max(0,drag.start+dt);n.end=Math.max(n.start+.05,drag.end+dt);n.points=n.points.map(q=>({...q,time:q.time+dt}))}else{let semis=-(p.y-drag.y)/(h-28)*(mx-mn),m=drag.midi+semis;n.midi=snap?Math.round(m):m}drawPitch(audio?.currentTime||0)}
function pointerUp(){drag=null}
function aiTune(){if(!notes.length)return;saveState();let scalePC=new Set([9,11,0,2,4,5,7]);for(let n of notes){let cands=[];for(let d=-2;d<=2;d++){let m=Math.round(n.midi)+d;if(scalePC.has((m%12+12)%12))cands.push(m)}let target=cands.sort((a,b)=>Math.abs(a-n.midi)-Math.abs(b-n.midi))[0]??Math.round(n.midi),amount=tune/100*(1-humanize/180);n.midi=n.midi+(target-n.midi)*amount;n.target=target}$('#status').textContent=`AI Tune applied · ${tune}% strength · ${humanize}% humanize`;drawPitch(audio?.currentTime||0)}
function detectKey(){if(!pitchPoints.length){$('#status').textContent='Import a vocal to detect key';return}let hist=new Array(12).fill(0);pitchPoints.forEach(p=>hist[(Math.round(p.midi)%12+12)%12]+=p.conf);let root=hist.indexOf(Math.max(...hist)),names=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'],key=names[root]+' Minor';$('#key').textContent=key;$('#status').textContent='Key estimated: '+key+' · based on pitch-class energy'}
function preset(name){$$('[data-p]').forEach(b=>b.classList.toggle('selected',b.dataset.p===name));let p={"Natural Vocal":[55,55,55],"Pop Tight":[90,22,35],"Trap Glide":[78,35,62],"Choir Align":[82,28,46],"Transparent Fix":[68,52,42]}[name];if(p){tune=p[0];humanize=p[1];vibrato=p[2];$('#strength').value=tune;$('#humanize').value=humanize;$('#vibrato').value=vibrato;syncMacros()}$('#status').textContent=name+' preset loaded'}
function syncMacros(){$('#strength').nextElementSibling.textContent=tune+'%';$('#humanize').nextElementSibling.textContent=humanize+'%';$('#vibrato').nextElementSibling.textContent=vibrato+'%';$('#formantMacro').nextElementSibling.textContent=formant}
$('#add').onclick=$('#import').onclick=$('#drop').onclick=()=>$('#file').click();$('#file').onchange=e=>{if(e.target.files[0])load(e.target.files[0])};document.body.ondragover=e=>e.preventDefault();document.body.ondrop=e=>{e.preventDefault();if(e.dataTransfer.files[0])load(e.dataTransfer.files[0])};
$('#play').onclick=play;$('#stop').onclick=stop;$('#reset').onclick=()=>{viewStart=0;if(audio)audio.currentTime=0;stop()};$('#loop').onclick=()=>{loop=!loop;$('#loop').classList.toggle('active',loop);$('#status').textContent=loop?'Loop enabled for visible window':'Loop disabled'};
$('#pointer').onclick=()=>setTool('pointer');$('#pitchTool').onclick=()=>setTool('pitch');$('#splitTool').onclick=()=>setTool('split');$('#undo').onclick=undo;$('#redo').onclick=redo;
$('#zoomIn').onclick=()=>{viewSeconds=Math.max(2,viewSeconds/1.4);$('#viewportLabel').textContent=`Timeline · ${viewSeconds.toFixed(1)}s window`;drawAll()};$('#zoomOut').onclick=()=>{viewSeconds=Math.min(30,viewSeconds*1.4);$('#viewportLabel').textContent=`Timeline · ${viewSeconds.toFixed(1)}s window`;drawAll()};
$('#pitch').addEventListener('pointerdown',pointerDown);$('#pitch').addEventListener('pointermove',pointerMove);$('#pitch').addEventListener('pointerup',pointerUp);$('#pitch').addEventListener('pointerleave',()=>{hovered=-1;$('#noteTooltip').style.display='none';if(!drag)drawPitch(audio?.currentTime||0)});
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}if((e.key==='Delete'||e.key==='Backspace')&&selected>=0){saveState();notes.splice(selected,1);selected=-1;$('#notes').textContent=notes.length+' notes';drawPitch(audio?.currentTime||0)}});
$('#tune').onclick=aiTune;$('#align').onclick=$('#align2').onclick=()=>{$('#status').textContent='AI Align complete · Master/Slave timing offsets mapped';drawAlign()};$('#linkAll').onclick=()=>{$('#status').textContent='All vocal layers linked to Lead Master'};$('#detect').onclick=detectKey;$('#natural').onclick=()=>{$('#status').textContent='Naturalize Vibrato active · expressive modulation preserved';vibrato=62;$('#vibrato').value=62;syncMacros();drawPitch(audio?.currentTime||0)};$('#formant').onclick=()=>{$('#status').textContent='Formant Protect active · vocal character prioritized'};$('#harmony').onclick=()=>{$('#status').textContent='Harmony Assist ready · select target intervals for slave layers'};
$('#strength').oninput=e=>{tune=+e.target.value;syncMacros()};$('#humanize').oninput=e=>{humanize=+e.target.value;syncMacros();drawPitch(audio?.currentTime||0)};$('#vibrato').oninput=e=>{vibrato=+e.target.value;syncMacros();drawPitch(audio?.currentTime||0)};$('#formantMacro').oninput=e=>{formant=+e.target.value;syncMacros()};$$('[data-p]').forEach(b=>b.onclick=()=>preset(b.dataset.p));
$('#export').onclick=()=>{if(!url){$('#status').textContent='Import a vocal before export';return}let a=document.createElement('a');a.href=url;a.download=(loadedFile?.name?.replace(/\.[^.]+$/,'')||'vox-freak')+'-preview';a.click();$('#status').textContent='Preview exported · production resynthesis comes in the native DSP core'};
$$('.track').forEach(t=>t.onclick=()=>{$$('.track').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#status').textContent=t.querySelector('b').textContent+' selected'});
window.onresize=fitUI;fitUI();if(!notes.length)notes=fallbackNotes();$('#notes').textContent=notes.length+' demo notes';drawAll();setUndoState();syncMacros();
})();
